- Dockerfile
- docker-entrypoint.sh
Fixed Docker container startup issue by simplifying the entrypoint configuration, using a local docker-entrypoint.sh file instead of trying to make it ephemeral, and consolidating database migration and application startup commands into a single CMD instruction in the Dockerfile.
> fix: docker setup

- sim/app/blocks/blocks/perplexity.ts
- sim/app/blocks/index.ts
- sim/app/tools/index.ts
- sim/app/tools/perplexity/chat.ts
- sim/app/tools/perplexity/index.ts
- sim/app/tools/perplexity/types.ts
Added the perplexity chat completions tool and block.
Fixes #107 
- [y] New feature (non-breaking change which adds functionality)
I ran the block with different configurations, providing a system prompt and not providing a system prompt and it works.
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] My changes generate no new warnings
- [y] I have added tests that prove my fix is effective or that my feature works
- [y] Any dependent changes have been merged and published in downstream modules
- [y] I have updated version numbers as needed (if needed)
- [y] My changes do not introduce any new security …
> feat[tools]: added perplexity tool

- sim/app/stores/workflows/workflow/store.ts
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/condition-input.tsx
There are two input variables (subblock) types in a block: string and array of objects, with keys id and cells (actual content). My code treats each kind separately. I use a regex to find a reference to the old name and replace it with the new name.
Fixes #120 
Created workflow with all basic types of blocks (Agent, API, Evaluator, Condition, Function, Router), created edges, and set output from the previous block to the target block as input on the target block. Then, I renamed the previous block and validated the name change I reflected in the input variable name.
I have also updated the condition block to follow the original commit that updated all other blocks.
> fix[ux]: referenced block renaming

- sim/app/blocks/blocks/starter.ts
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/providers/github-config.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/copyable.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/webhook-footer.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/webhook-header.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/webhook-url.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx
Added github webhook with instructions on how to set it up
Fixes #113
> feat[webhook]: added github webhook

- sim/app/api/scheduled/[id]/route.ts
- sim/app/api/scheduled/execute/route.ts
- sim/app/api/scheduled/route.ts
- sim/app/w/[id]/components/workflow-block/components/action-bar/schedule-status.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/components/schedule-modal.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/schedule-config.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/sub-block.tsx
- sim/app/w/[id]/components/workflow-block/workflow-block.tsx
- sim/blocks/blocks/starter.ts
- sim/blocks/types.ts
- sim/lib/utils.ts
- sim/stores/workflows/sync.ts
- vercel.json
Scheduled workflows were not running bc the path at vercel.json was wrong, and I fixed that. Also, we moved the configuration of a schedule into a modal to make it more similar to the webhook. Now, when they configure their schedule it gets saved to the DB right away and not during the auto-syncing. This makes more sense since this likely won't change frequently so we shouldn't repeatedly sync it.
Fixes #146 
I configured a workflow and ensured that I was able to see it. We were also correctly displaying 'next run at' to the user. We need to deploy the changes to see if the cron job executes the scheduled workflows that are due for execution.
Starter block with schedule:
Modal to configure schedule:
> fix[schedule]: fix cron job to execute scheduled workflows not running, update styling for schedules to show visual indication that schedule is active

- sim/app/w/[id]/components/control-bar/components/notification-dropdown-item/notification-dropdown-item.tsx
- sim/app/w/[id]/components/control-bar/control-bar.tsx
- sim/app/w/[id]/components/notifications/notifications.tsx
- sim/app/w/[id]/components/workflow-block/workflow-block.tsx
- sim/app/w/[id]/hooks/use-workflow-execution.ts
- sim/app/w/[id]/workflow.tsx
- sim/executor/index.test.ts
- sim/executor/index.ts
- sim/executor/types.ts
- sim/stores/execution/store.ts
- sim/stores/notifications/types.ts
Added a debug mode and relevant tests
Fixes #77 
Added a test, ran through manual examples and confirmed that I was able to debug in order of block execution. Also works on parallel blocks. and debugs them together. Resume till end works as well.
Debug Mode UI:
> feat(debug): added debug mode & tests

- .github/PULL_REQUEST_TEMPLATE.md
- sim/app/api/__test-utils__/setup.ts
- sim/app/api/__test-utils__/utils.ts
- sim/app/api/schedules/execute/route.test.ts
- sim/app/api/webhooks/trigger/[path]/route.test.ts
- sim/app/api/workflows/[id]/execute/route.test.ts
- sim/executor/index.test.ts
- sim/vitest.config.ts
- **added tests for new executor error path**
- **added integration tests for executions for different trigger types**
- **updated PR template to include checkbox item on tests**
Added additional unit tests for executor, added integration tests for execution API routes
Fixes #155 
Ran the tests and they all pass, we already run the test when a PR is opened or a commit is pushed.
> tests(integration): added additional unit tests for executor, added integration tests for execution API routes

- packages/sdk/src/types/index.ts
- packages/sdk/src/workflows/builder.ts
- sim/app/api/function/execute/route.ts
- sim/app/w/[id]/components/workflow-block/components/connection-blocks/connection-blocks.tsx
- sim/app/w/[id]/components/workflow-loop/components/loop-input/loop-input.tsx
- sim/app/w/[id]/components/workflow-loop/components/loop-label/loop-label.tsx
- sim/app/w/[id]/components/workflow-loop/workflow-loop.tsx
- sim/components/ui/tag-dropdown.tsx
- sim/executor/index.test.ts
- sim/executor/index.ts
- sim/executor/loops.ts
- sim/executor/resolver.ts
- sim/executor/types.ts
- sim/serializer/__test-utils__/test-workflows.ts
- sim/serializer/index.test.ts
- sim/serializer/types.ts
- sim/stores/workflows/workflow/store.ts
- sim/stores/workflows/workflow/types.ts
Separated loops into for and forEach. 
Run loops and add values to get currentItem, items, or index in loop cycle.
> feat(loops)

- README.md
Added gh star history chart to show the explosive growth 🚀
> Add GitHub star history to readme

- sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx
Added credential selector for agent tools that require oauth
Tested gmail tool manually, confirmed that it works.
> feat(agent): added credential selector for agent tools that require oauth

- sim/app/w/marketplace/components/workflow-card.tsx
- sim/app/w/marketplace/constants/categories.tsx
- sim/db/migrations/0024_next_whizzer.sql
- sim/db/migrations/meta/0024_snapshot.json
- sim/db/migrations/meta/_journal.json
- sim/db/schema.ts
- sim/stores/workflows/registry/store.ts
- sim/stores/workflows/registry/types.ts
Created the ability for users to check out marketplace workflows. 
> feat(marketplace): adding marketplace workflow to registry

- sim/app/api/marketplace/[id]/info/route.ts
- sim/app/api/marketplace/[id]/unpublish/route.ts
- sim/app/api/marketplace/publish/route.ts
- sim/app/api/marketplace/workflows/route.ts
- sim/app/api/workflows/sync/route.ts
- sim/app/w/[id]/components/control-bar/components/marketplace-modal/marketplace-modal.tsx
- sim/app/w/[id]/workflow.tsx
- sim/app/w/components/sidebar/components/folder-section/folder-section.tsx
- sim/app/w/components/sidebar/components/nav-item/nav-item.tsx
- sim/app/w/components/sidebar/sidebar.tsx
- sim/app/w/marketplace/components/workflow-card-skeleton.tsx
- sim/app/w/marketplace/components/workflow-card.tsx
- sim/app/w/marketplace/components/workflow-preview.tsx
- sim/app/w/marketplace/marketplace.tsx
- sim/components/ui/loading-agent.tsx
- sim/db/migrations/0027_careless_gamora.sql
- sim/db/migrations/meta/0027_snapshot.json
- sim/db/migrations/meta/_journal.json
- sim/db/schema.ts
- sim/stores/workflows/registry/types.ts
- sim/stores/workflows/sync.ts
Improved marketplace, sidebar, and added loading animation. 
Fixes #187 
> improvement: marketplace, sidebar, loading

- sim/app/w/[id]/components/control-bar/control-bar.tsx
- sim/app/w/[id]/components/notifications/notifications.tsx
- sim/app/w/[id]/hooks/use-workflow-execution.ts
- **ensure that the run button accurately reflects the execution state**
- **added cancellation for workflows with multiple runs, fixed styling of info notification**
allow cancellation of workflow run, fix styling for info notification
Tested manually many times and it works.
> feat(cancel): allow cancellation of workflow run, fix styling for info notification

- sim/app/api/function/execute/route.ts
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/condition-input.tsx
- sim/blocks/blocks/evaluator.ts
- sim/executor/handlers/evaluator/evaluator-handler.ts
- sim/executor/resolver.ts
Fixed evaluator toLowerCase issue, function block error handling, & reverted condition block edges fix in condition-input.tsx to old state.
Manual tests, unit tests passing.
> fix(bugs): fixed evaluator toLowerCase issue, function block error handling, & reverted condition block edges fix

- sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/components/schedule-modal.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/schedule-config.tsx
- sim/app/w/[id]/components/workflow-block/workflow-block.tsx
- sim/lib/schedule-utils.ts
- sim/stores/workflows/registry/store.ts
- sim/stores/workflows/workflow/store.ts
Fixes the logic and styling of the schedule block. Now, schedules are maintained through the sync (not direct API access).
Create/delete schedules
> fix(schedule): deletion logic and styling

- sim/app/api/files/parse/route.ts
- sim/blocks/blocks/file.ts
- sim/tools/file/parser.ts
- sim/tools/file/types.ts
Added URL upload for our file parser
I tested this manually by providing a URL and by adding files like before, and we successfully parse both. Since the URL upload requires us to download the file to S3, we don't enable the URL locally, we only do it in prod.
> feat(parser): added URL upload for our file parser

- README.md
This pull request includes a minor update to the `README.md` file, correcting the X(Twitter) handle.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8-R8): Corrected the Twitter badge link to accurately reflect the `simstudioai` X(Twitter) handle.
Use the rich diff to display the change.
> Fix X handle in the README badge

- docs/next.config.ts
> docs home page link fix

- sim/app/api/workflows/[id]/variables/route.ts
- sim/app/w/[id]/components/panel/components/variables/variables.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/long-input.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/short-input.tsx
- sim/components/ui/formatted-text.tsx
- sim/executor/handlers/api/api-handler.ts
- sim/executor/resolver.test.ts
- sim/executor/resolver.ts
- sim/lib/variables/variable-manager.test.ts
- sim/lib/variables/variable-manager.ts
- sim/stores/panel/variables/types.ts
- sim/tools/http/request.ts
- sim/tools/types.ts
- sim/tools/utils.test.ts
- sim/tools/utils.ts
- **variableType updated to include plain type, resolution logic enhanced**
- **added tests, ensure that short and long input can also resolve plaintext value**
Added new variableType 'plain', resolution logic enhanced
Fixes #245 
Tested manually with many different configurations, and in every case we were able to resolve the values correctly. 
> fix(variables): added new variableType 'plain', resolution logic enhanced

- sim/app/api/webhooks/trigger/[path]/route.test.ts
- sim/app/w/[id]/hooks/use-workflow-execution.ts
- sim/app/w/logs/components/sidebar/sidebar.tsx
- sim/app/w/logs/components/trace-spans/trace-spans-display.tsx
- sim/app/w/logs/logs.tsx
- sim/app/w/logs/stores/types.ts
- sim/blocks/blocks/exa.ts
- sim/executor/index.test.ts
- sim/executor/index.ts
- sim/executor/types.ts
- sim/lib/logs/execution-logger.ts
- sim/lib/logs/trace-spans.ts
- sim/tools/exa/getContents.ts
- sim/tools/exa/types.ts
- sim/tools/sheets/update.ts
- sim/tools/x/user.ts
- **fixed tools that needed better error handling, slight modifications**
- **improvement: fixed the pulsing for blocks that were already completed by tracking the active blocks being executed**
- **fixed total duration calculation, fixed trace spans for parallel executions**
Enhanced error handling for some tools, ensured that we have tested everything & fixed parallel execution trace spans
Fixes #262, #110 
Tested all tools and blocks manually, tested trace spans for both manual and parallel execution
> fix(tools): enhanced error handling for some tools, ensured that we have tested everything & fixed parallel execution trace spans

- sim/app/api/proxy/route.ts
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/credential-selector/components/oauth-required-modal.tsx
- sim/blocks/blocks/notion.ts
- sim/lib/auth.ts
- sim/lib/oauth.ts
- sim/tools/index.ts
- sim/tools/notion/createPage.ts
- sim/tools/notion/index.ts
- sim/tools/notion/read.ts
- sim/tools/notion/types.ts
- sim/tools/notion/updatePage.ts
- sim/tools/notion/write.ts
Added notion oauth, tools, & block
Fixes #263, #103 
Tested these all manually, ensured that they work.
> feat(tools): added notion oauth, tools, & block

- sim/app/w/[id]/components/control-bar/control-bar.tsx
- sim/app/w/[id]/components/panel/components/chat/chat.tsx
- sim/app/w/[id]/components/panel/components/chat/components/chat-message.tsx
- sim/app/w/[id]/components/panel/components/console/console.tsx
- sim/app/w/[id]/components/panel/components/variables/variables.tsx
- sim/app/w/[id]/components/panel/panel.tsx
- sim/app/w/[id]/hooks/use-workflow-execution.ts
- sim/executor/index.ts
- sim/stores/panel/chat/store.ts
- sim/stores/panel/chat/types.ts
- sim/stores/panel/console/store.ts
- sim/stores/panel/console/types.ts
- sim/stores/panel/types.ts
You can now chat with your workflows in order to dynamically test inputting different things and see the resulting execution.
1. Create a workflow
2. Drag the start input into one of the blocks
3. Select an output in the chat
4. Send a message
5. See result in chat
> feat(workflow-chat)

- sim/app/api/proxy/image/route.ts
- sim/app/api/proxy/tts/route.ts
- sim/app/w/[id]/components/panel/components/console/components/audio-player/audio-player.tsx
- sim/app/w/[id]/components/panel/components/console/components/json-view/json-view.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx
- sim/blocks/blocks/elevenlabs.ts
- sim/blocks/index.ts
- sim/components/icons.tsx
- sim/tools/elevenlabs/index.ts
- sim/tools/elevenlabs/tts.ts
- sim/tools/elevenlabs/types.ts
- sim/tools/openai/dalle.ts
- sim/tools/registry.ts
- added elevenlabs tools/block (not streaming)
- added audio-player console component
- consolidated proxy routes
Tested manually, works great
> feat(tools): added elevenlabs tools/block, added audio-player console component, modified proxy routes

- sim/providers/google/index.ts
- sim/providers/model-capabilities.test.ts
- sim/providers/model-capabilities.ts
- sim/providers/pricing.ts
- sim/providers/utils.ts
- openai compatibility layer for google was buggy
- so we moved to google genai sdk
- but it is a known issue that google does not support tool calling and structured output at the same timehttps://github.com/openai/openai-agents-python/issues/236
Fixes #284 
Tested manually a bunch of times
> fix(google): moved gemini to google genai sdk instead openai compatibility layer

- sim/app/api/schedules/schedule/route.ts
- sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/schedule-config.tsx
- sim/app/w/[id]/components/workflow-block/workflow-block.tsx
- sim/blocks/index.ts
- sim/db/migrations/0029_grey_barracuda.sql
- sim/db/migrations/meta/0029_snapshot.json
- sim/db/migrations/meta/_journal.json
- sim/db/schema.ts
- sim/lib/schedules/utils.test.ts
- sim/lib/schedules/utils.ts
- sim/lib/utils.ts
- sim/lib/webhooks/utils.ts
- **fixed scheduling**
- **added timezone to db, still store in utc but for displaying schedule for users**
The scheduling logic did not account for different days in different timezones, so we needed to account for that. Also, the schedule that was displayed to the user was localized and didn't account for the timezone, so we saved the timezone selected to the DB and display it to the user.
Tested manually with different timezones, different times. Also added a ton of unit tests.
https://github.com/user-attachments/assets/8b6af288-164f-492b-8c9b-46d77317fbe1
> fix(schedule): fixed scheduling

- sim/tools/s3/get_object.ts
> -fixed request to send the timestamp in utc rather than system time

- sim/blocks/blocks/mem0.ts
- sim/tools/mem0/add_memories.ts
Styled mem0 tool
Reorganized the fields on the block.
> mem0 styling

- sim/app/w/[id]/components/workflow-block/components/sub-block/components/slider-input.tsx
- sim/app/w/[id]/components/workflow-block/components/sub-block/sub-block.tsx
- sim/blocks/blocks/mem0.ts
- sim/blocks/types.ts
- sim/package-lock.json
- sim/tools/mem0/add_memories.ts
- sim/tools/mem0/get_memories.ts
- sim/tools/mem0/search_memories.ts
Improved the mem0 subblocks and removed unnecessary parameters. 
> improvement(mem0)

- sim/.gitignore
- sim/app/global-error.tsx
- sim/instrumentation-client.ts
- sim/instrumentation.ts
- sim/next.config.ts
- sim/package-lock.json
- sim/package.json
- sim/sentry.edge.config.ts
- sim/sentry.server.config.ts
Added error tracking in prod using sentry
Tested and ensured that we receive sample errors in sentry for our org. There is no additional tracking done in development.
> feat(errors): added error tracking in prod using sentry

- docs/content/docs/tools/slack.mdx
Added the link to slack demo vid
> improvement(slack): added Slack demo YouTube video

- sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/webhook-config.tsx
- sim/app/w/components/workflow-preview/generic-workflow-preview.tsx
- sim/stores/workflows/workflow/store.ts
Added logic to read the webhook configuration in the deployed preview which was previously causing workflow to fail. Added logic to remove the webhook values in the DB when a user deletes the webhook config. 
I tested this by adding web hooks, deleting them, checking the DB schema, running revert to deployed, and making sure the states were getting updated to take into account changes with the webhook configuration. Tested on many different workflows of varying complexity.
> improvement(deployed preview): fixed webhook config that was causing workflow failure in deployed state 

- sim/app/(auth)/verify/page.tsx
- sim/app/api/chat/edit/[id]/route.ts
- sim/app/w/[id]/components/control-bar/components/deploy-modal/components/chat-deploy/chat-deploy.tsx
- sim/lib/urls/utils.ts
- sim/middleware.ts
- sim/tools/http/request.ts
- sim/tools/mistral/parser.ts
- sim/tools/openai/dalle.ts
removed duplicate logic to get base url with fallback, made util to fetch the base url
Tested chat deploy and ensured that it still worked. The reason we created a separate util file since the rest of the utils file is used in the edge runtime, which doesn't support the `crypto` module
> improvement(utils): removed duplicate logic to get base url with fallback, made util

- apps/sim/app/api/workflows/[id]/variables/route.ts
- apps/sim/app/w/[id]/components/panel/components/variables/variables.tsx
- apps/sim/blocks/blocks/function.ts
- apps/sim/executor/index.ts
- apps/sim/executor/resolver.test.ts
- apps/sim/executor/resolver.ts
- apps/sim/lib/variables/variable-manager.test.ts
- apps/sim/lib/variables/variable-manager.ts
- apps/sim/stores/panel/variables/store.ts
- apps/sim/stores/panel/variables/types.ts
- apps/sim/tools/function/execute.test.ts
- apps/sim/tools/function/execute.ts
- apps/sim/tools/function/types.ts
Fixed inputting values, consolidated string and plain text, and fixed syncing. 
Fixes #346
> improvement(variables): variable experience and removed execution time

- apps/sim/app/w/logs/components/sidebar/components/markdown-renderer.tsx
- apps/sim/app/w/logs/components/sidebar/sidebar.tsx
- apps/sim/app/w/logs/logs.tsx
- apps/sim/app/w/logs/stores/store.ts
- apps/sim/app/w/logs/stores/types.ts
- apps/sim/executor/index.ts
- apps/sim/executor/types.ts
- apps/sim/lib/logs/execution-logger.ts
- apps/sim/lib/utils.ts
- apps/sim/stores/panel/console/store.ts
Added infinite scroll, markdown rendering, and individual block input to logs
Tested every block type, and all execution types and ensured that we are receiving block input and output correctly,
> improvement(logs): added infinite scroll, markdown rendering, and individual block input to logs

- docker-compose.local.yml
- docker-compose.prod.yml
Add variable support to docker compose for postgres with defaults so it can be picked up by PaaS such as Coolify and be changeable without editing the compose file.
> chore(docker): update compose to support db variables with defaults

- apps/docs/package.json
- apps/docs/tsconfig.json
- apps/sim/package.json
- apps/sim/tsconfig.json
- bun.lock
- package.json
- packages/simstudio/package.json
- packages/simstudio/tsconfig.json
- packages/tsconfig/base.json
- packages/tsconfig/library.json
- packages/tsconfig/nextjs.json
- packages/tsconfig/package.json
- tsconfig.json
Add tsconfig pkg to share across packages in monorepo
> feat(package): add tsconfig pkg to share across packages in monorepo

- apps/sim/executor/handlers/agent/agent-handler.ts
- apps/sim/executor/index.ts
Added ability to stream back responses for agent even if there are downstream blocks
Tested manually, ensured that the logs are still correct and that regardless of the workflow state, if the block is selected for output and the execution type is chat, that we stream the response back.
> fix(stream): added ability to stream back responses for agent even if there are downstream blocks

- apps/sim/app/api/workflows/[id]/execute/route.ts
- apps/sim/next.config.ts
Allow workflow executions via API in the browser
> fix(cors): allow workflow executions via API in the browser

- apps/docs/content/docs/tools/github.mdx
- apps/docs/content/docs/tools/google_docs.mdx
- apps/docs/content/docs/tools/google_drive.mdx
- apps/docs/content/docs/tools/jina.mdx
- apps/docs/content/docs/tools/mem0.mdx
- apps/docs/content/docs/tools/memory.mdx
- apps/docs/content/docs/tools/meta.json
- apps/docs/content/docs/tools/pinecone.mdx
- apps/docs/content/docs/tools/reddit.mdx
- apps/docs/content/docs/tools/s3.mdx
- apps/docs/content/docs/tools/serper.mdx
- apps/docs/content/docs/tools/typeform.mdx
- apps/docs/content/docs/tools/x.mdx
- apps/docs/content/docs/tools/youtube.mdx
- apps/sim/tools/memory/add.ts
- apps/sim/tools/memory/delete.ts
- apps/sim/tools/memory/get.ts
- apps/sim/tools/memory/get_all.ts
- apps/sim/tools/memory/index.ts
- apps/sim/tools/openai/image.ts
- scripts/generate-block-docs.ts
Added docs for memories, fixed styling
Nothing changed, just syntax
> fix(docs): fixed naming semantics for memory tools, updated doc generator, & included docs for memory block

- apps/sim/app/api/proxy/route.ts
- apps/sim/tools/http/request.test.ts
- apps/sim/tools/http/request.ts
fixed POST request for API blocks
Fixes https://github.com/simstudioai/sim/issues/390 
Tested https://postman-echo.com/post with a POST and a body and ensured that it works. Tested https://postman-echo.com/get with a GET as well
> fix(api): fixed POST request for API blocks

- apps/sim/.env.example
- apps/sim/app/api/files/delete/route.ts
- apps/sim/blocks/blocks/file.ts
- apps/sim/blocks/blocks/mistral_parse.ts
- apps/sim/lib/env.ts
- apps/sim/lib/uploads/setup.ts
Re-enabled file upload for mistral & url for file upload
Tested in a mock prod environment, ensured that I could upload/url for both mistral + file upload
> fix(file-upload): re-enabled file upload for mistral & url for file upload

- apps/docs/content/docs/tools/file.mdx
- apps/docs/content/docs/tools/mistral_parse.mdx
- apps/sim/app/api/logs/route.test.ts
- apps/sim/app/api/logs/route.ts
- apps/sim/app/w/logs/components/control-bar/control-bar.tsx
- apps/sim/app/w/logs/components/filters/components/workflow.tsx
- apps/sim/app/w/logs/logs.tsx
- apps/sim/app/w/logs/stores/store.ts
- apps/sim/app/w/logs/stores/types.ts
- scripts/generate-block-docs.ts
Fix log filtering by moving filtering to server-side, less load on client since server only responds with the logs that satisfy the filter criteria. Better API design, more performant logs, reduced memory usage. Filter store also still manages the filter state management, query building, and pagination/loading state
Tested with all variations, ensured that the filtering worked with pagination and no UX issues.
> fix(logs): fix log filtering by moving filtering to server-side, less load on client

- apps/sim/app/api/files/parse/route.test.ts
- apps/sim/app/api/files/parse/route.ts
- apps/sim/app/api/function/execute/route.ts
- apps/sim/app/api/providers/route.ts
- apps/sim/app/chat/[subdomain]/chat-client.tsx
- apps/sim/app/chat/[subdomain]/components/message-container/message-container.tsx
- apps/sim/executor/handlers/agent/agent-handler.test.ts
- apps/sim/executor/handlers/agent/agent-handler.ts
- apps/sim/executor/handlers/agent/types.ts
- apps/sim/executor/handlers/function/function-handler.test.ts
- apps/sim/executor/handlers/function/function-handler.ts
- apps/sim/providers/anthropic/index.ts
- apps/sim/providers/deepseek/index.ts
- apps/sim/providers/google/index.ts
- apps/sim/providers/openai/index.ts
- apps/sim/providers/types.ts
- apps/sim/stores/custom-tools/store.ts
- apps/sim/tools/function/execute.test.ts
- apps/sim/tools/function/execute.ts
- apps/sim/tools/function/types.ts
- apps/sim/tools/index.ts
- apps/sim/tools/utils.ts
- **refactored agent handler, fixed envvar resolution for function block**
- **resolve missing envvar resolution from function execution for custom tool**
Simplify agent handler, update tests, fix resolution of envvars in function execution
Tested various workflows and ensured that we can now run this manually, via api, via chat, etc.
> refactor(agent-handler): simplify agent handler, update tests, fix resolution of env vars in function execution

- apps/sim/blocks/blocks/google_calendar.ts
- apps/sim/tools/google_calendar/index.ts
- apps/sim/tools/google_calendar/invite.ts
- apps/sim/tools/google_calendar/types.ts
- apps/sim/tools/google_calendar/update.ts
- apps/sim/tools/registry.ts
Adde Google Calendar invite tool. 
Have an event and invite a user by either replacing attendees or adding to existing attendees.
> feat(gcal-invite): added google calendar invite tool

- apps/sim/app/api/knowledge/[id]/documents/[documentId]/chunks/route.ts
- apps/sim/app/api/knowledge/search/route.ts
- apps/sim/lib/webhooks/utils.ts
- apps/sim/tools/knowledge/search.ts
- apps/sim/tools/knowledge/upload_chunk.ts
Webhooks trying to access the session with getSession would error, so I gave the knowledge tools access to workflowId to prevent authentication errors. I added the workflow ID as context to support webhook authentication.
I recreated these errors in development for both searching and uploading to knowledge base and confirmed that my changes solved the Unauthorized error.
> fix(knowledge-wh): fixed authentication error on webhook trigger

- apps/sim/.env.example
added `NEXT_PUBLIC_APP_URL` to .env.example
Fixes #481
> fix(env): added NEXT_PUBLIC_APP_URL to .env.example

- apps/sim/app/chat/[subdomain]/components/input/input.tsx
made the chat mobile friendly, the chat input placeholder was overflowing
> fix(deployed-chat): made the chat mobile friendly

- apps/sim/app/chat/[subdomain]/chat-client.tsx
- apps/sim/app/chat/[subdomain]/components/header/header.tsx
- apps/sim/app/chat/[subdomain]/components/input/input.tsx
- apps/sim/app/chat/[subdomain]/components/input/voice-input.tsx
- apps/sim/app/chat/[subdomain]/components/voice-interface/components/particles.tsx
Improved the chat deploy ui/ux on mobile, desktop, and for voice.
> improvement(ui/ux): chat deploy

- apps/sim/app/w/[id]/components/notifications/notifications.tsx
- apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/schedule/components/schedule-modal.tsx
- apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/confirmation.tsx
- apps/sim/app/w/components/sidebar/components/folder-tree/components/folder-item.tsx
- apps/sim/app/w/components/sidebar/components/settings-modal/components/general/general.tsx
- apps/sim/app/w/knowledge/[id]/base.tsx
- apps/sim/blocks/blocks/huggingface.ts
- apps/sim/blocks/blocks/workflow.ts
- apps/sim/components/icons.tsx
Fix the UI for folder deletion, huggingface icon, workflow block icon, standardized alert dialog
UI changes, no testing neccessary
> fix(ui): fix the UI for folder deletion, huggingface icon, workflow block icon, standardized alert dialog

- apps/sim/db/migrations/0046_loose_blizzard.sql
- apps/sim/db/migrations/meta/0046_snapshot.json
- apps/sim/db/migrations/meta/_journal.json
- apps/sim/db/schema.ts
Same PR as feature/access-control-permissions but just the db migration changes so we can do those first
> PR: changes for migration

- apps/sim/app/api/workflows/[id]/deploy/route.test.ts
- apps/sim/app/api/workflows/[id]/variables/route.ts
- apps/sim/app/api/workspaces/[id]/permissions/route.ts
- apps/sim/app/api/workspaces/invitations/route.ts
- apps/sim/app/api/workspaces/members/route.ts
- apps/sim/app/w/[id]/components/control-bar/components/deployment-controls/deployment-controls.tsx
- apps/sim/app/w/[id]/components/control-bar/control-bar.tsx
- apps/sim/app/w/[id]/components/toolbar/toolbar.tsx
- apps/sim/app/w/[id]/components/workflow-block/workflow-block.tsx
- apps/sim/app/w/[id]/workflow.tsx
- apps/sim/app/w/components/providers/providers.tsx
- apps/sim/app/w/components/providers/workspace-permissions-provider.tsx
- apps/sim/app/w/components/sidebar/components/invite-modal/invite-modal.tsx
- apps/sim/app/w/components/sidebar/components/invite-modal/invites-sent/invites-sent.tsx
- apps/sim/app/w/components/sidebar/components/workspace-header/workspace-header.tsx
- apps/sim/app/w/components/sidebar/sidebar.tsx
- apps/sim/hooks/use-user-permissions.ts
- apps/sim/lib/email/utils.test.ts
- apps/sim/lib/email/utils.ts
- apps/sim/lib/permissions/utils.test.ts
- apps/sim/lib/permissions/utils.ts
This PR includes workspace permissions improvements with 85% reduction in API calls:
- Improved permissions UI & access patterns, show outstanding invites
- Added logger for better debugging
- Added provider for workspace permissions with significant performance improvements
**Performance improvements:**
- 85% reduction in API calls to get user permissions
- Improved performance for invitations
> improvement(permissions): workspace permissions improvements, added provider and reduced API calls by 85%

- apps/sim/socket-server/index.ts
Remove sockets debug logs. 
No change to functionality
> fix(socket logs): remove debug sockets logs

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/user-avatar-stack/user-avatar-stack.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-header/workspace-header.tsx
- apps/sim/app/workspace/[workspaceId]/w/hooks/use-registry-loading.ts
- apps/sim/app/workspace/[workspaceId]/w/page.tsx
- apps/sim/components/ui/loading-agent.tsx
- apps/sim/hooks/use-collaborative-workflow.ts
- apps/sim/socket-server/handlers/connection.ts
- apps/sim/socket-server/handlers/operations.ts
- apps/sim/socket-server/handlers/workflow.ts
> improvement(sockets): fixed positioning of blocks recalc, hydration issue with workspaceId, and presence

- apps/sim/db/index.ts
Implementing bug fix described here -- https://github.com/orgs/supabase/discussions/21789#discussioncomment-9912393
> fix(global conn): make db connection global to not reinstatiate on every import 

- apps/sim/db/index.ts
Frontloading db change improvement. Should resolve supabase timeouts. 
> fix(db conn): db connection issue 

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/action-bar/action-bar.tsx
- apps/sim/hooks/use-collaborative-workflow.ts
- apps/sim/socket-server/database/operations.ts
- apps/sim/socket-server/middleware/permissions.ts
- apps/sim/socket-server/validation/schemas.ts
Socket events for Duplicate Block + vertical handles 
> fix(sockets events): remaining sockets events

- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-header/workspace-header.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
- apps/sim/app/workspace/[workspaceId]/w/page.tsx
- apps/sim/stores/workflows/registry/store.ts
- apps/sim/stores/workflows/registry/types.ts
fix switch workspace fully + first workflow should be selected when you enter app
> fix(workspaces init): fix switch workspace fully + first workflow should be selected when you enter app

- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
- apps/sim/app/workspace/[workspaceId]/w/page.tsx
- apps/sim/stores/workflows/registry/store.ts
- apps/sim/stores/workflows/registry/types.ts
> Revert "fix(workspaces init): fix switch workspace fully + first workflow should be selected when you enter app"

- apps/sim/app/api/workflows/[id]/execute/route.ts
Check for concurrent requests is not correct. 
> fix(concurrent reqs): concurrent request checks bug 

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/user-avatar-stack/components/connection-status/connection-status.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/user-avatar-stack/user-avatar-stack.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/control-bar.tsx
If socket is disconnected for 6 seconds -- warning shows up. 
Turn off sockets server for 6 seconds and see if it pops up. On reconnect the warning goes away. 
https://github.com/user-attachments/assets/71453544-97d4-4cbd-95f8-2159dc6a2e36
>  improvement(sockets conn): sockets connection refresh warning

- apps/sim/providers/models.ts
Added temp controls for gpt-4.1 family of models upon customer request. 
Tested all of the 3 changed models with temperatures ranging from 0-2 and confirmed that they worked.
> feat(models): added temp controls for gpt-4.1 family of models

- apps/docs/content/docs/tools/knowledge.mdx
- apps/sim/app/api/chat/utils.ts
- apps/sim/app/api/function/execute/route.test.ts
- apps/sim/app/api/function/execute/route.ts
- apps/sim/app/api/schedules/execute/route.test.ts
- apps/sim/app/api/schedules/execute/route.ts
- apps/sim/app/api/webhooks/trigger/[path]/route.test.ts
- apps/sim/app/api/webhooks/trigger/[path]/route.ts
- apps/sim/app/api/workflows/[id]/deploy/route.test.ts
- apps/sim/app/api/workflows/[id]/deploy/route.ts
- apps/sim/app/api/workflows/[id]/execute/route.test.ts
- apps/sim/app/api/workflows/[id]/execute/route.ts
- apps/sim/blocks/blocks/knowledge.ts
- apps/sim/db/schema.ts
- apps/sim/executor/handlers/workflow/workflow-handler.ts
- apps/sim/lib/documents/document-processor.ts
- apps/sim/lib/webhooks/utils.ts
- apps/sim/providers/models.ts
- apps/sim/providers/utils.test.ts
- apps/sim/stores/workflows/registry/store.ts
- apps/sim/tools/function/execute.test.ts
- apps/sim/tools/function/execute.ts
- apps/sim/tools/knowledge/create_document.ts
- apps/sim/tools/knowledge/index.ts
- apps/sim/tools/knowledge/types.ts
- apps/sim/tools/registry.ts
Change Log: 
- remove the usage of state column in all tables
- function block upgrades
- 4.1 family of models has temp
- knowledgebase create tool in workflow
- persist for selector components like kb selector, channel selector, etc
> v0.2.4: feat, improvement, fix

- apps/docs/content/docs/introduction/index.mdx
fixed broken docs links 
Fixes #623 
NA
> fix(docs): fixed broken docs links

- apps/sim/providers/models.ts
> feat(models): add grok-4

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx
fixed double scrollbar issue 
Tested manually, provided images below
Before:
After:
> fix(scrollbar): fixed double scrollbar

- apps/docs/content/docs/tools/gmail.mdx
- apps/sim/blocks/blocks/gmail.ts
- apps/sim/tools/gmail/draft.ts
- apps/sim/tools/gmail/index.ts
- apps/sim/tools/registry.ts
Added gmail draft operation
Testing drafting email 
https://github.com/user-attachments/assets/ba0f7525-3c4b-43a9-bcee-a2e7677f3218
> improvement(gmail): added gmail draft operation

- apps/sim/tools/http/request.ts
Increase API block timeout to 2 min.
> fix(api-timeout): increase timeout for API block to 2 min

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/hooks/use-sub-block-value.ts
- apps/sim/stores/operation-queue/store.ts
Remove hacky debounce logic [we were debouncing first and then adding to queue] -- and replace with debouncing native to the operation queue. Subblock ops are directly debounced. 
Make large deletions / additions when offline [sockets server off] and come back online -- other tabs should be replayed correctly. Can also test with wand.
> fix(queueing): make debouncing native to queue

- apps/sim/stores/panel/console/store.ts
> fix(console): match by execution & block id when updating console-entry

- apps/sim/app/api/knowledge/[id]/documents/route.test.ts
- apps/sim/app/api/knowledge/[id]/documents/route.ts
- apps/sim/app/api/knowledge/utils.test.ts
- apps/sim/app/api/knowledge/utils.ts
- apps/sim/app/workspace/[workspaceId]/knowledge/[id]/[documentId]/document.tsx
- apps/sim/app/workspace/[workspaceId]/knowledge/[id]/base.tsx
- apps/sim/app/workspace/[workspaceId]/knowledge/components/search-input/search-input.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/document-selector/document-selector.tsx
- apps/sim/components/ui/search-highlight.tsx
- apps/sim/hooks/use-knowledge.ts
- apps/sim/stores/knowledge/store.ts
- Add Pagination for Docs
- Remove problematic KB col count update 
Tested pagination manually by adding 1100 docs
> improvement(kb): pagination for docs + remove kb token count problematic query 

- apps/sim/db/index.ts
Can have much higher cap on max connections for prod. 
- [] All tests pass locally and in CI (`bun run test`)
> improvement(concurrent-conn): upgraded supabase instance to support more connections

- apps/sim/db/index.ts
- apps/sim/socket-server/database/operations.ts
- apps/sim/socket-server/rooms/manager.ts
Increase sockets db allocations. Mostly for buffer.
> improvement(sockets): increase buffer for connections 

- apps/sim/db/index.ts
- apps/sim/socket-server/database/operations.ts
- apps/sim/socket-server/rooms/manager.ts
Increase DB limits further to not hit timeouts in the near term.
> improvement(db): further increase db limits

- apps/docs/content/docs/connections/data-structure.mdx
- apps/docs/content/docs/getting-started/index.mdx
> minor docs fix

- apps/sim/app/chat/[subdomain]/chat-client.tsx
- apps/sim/app/chat/[subdomain]/components/voice-interface/voice-interface.tsx
- Add UI to interrupt voice agent. Can press spacebar -- clean UI
- Live subtitle like transcription for user input 
- Mute mic while agent is talking to it doesn't hear it's own audio and keep going
https://github.com/user-attachments/assets/5df64ccd-5977-4b27-a3dc-015d62058e6d
> improvement(voice): interrupt UI + mute mic while agent is talking

- apps/sim/app/chat/[subdomain]/components/voice-interface/voice-interface.tsx
- apps/sim/executor/routing/routing.test.ts
- apps/sim/executor/routing/routing.ts
- apps/sim/executor/tests/parallel-activation-integration.test.ts
- apps/sim/executor/tests/parallel-activation-regression.test.ts
> fix(subflows): fixed subflows not executing

- apps/sim/db/migrations/0054_naive_raider.sql
- apps/sim/db/migrations/meta/0054_snapshot.json
- apps/sim/db/migrations/meta/_journal.json
- apps/sim/db/schema.ts
remove the unused workspace_member table in favor of permissions
Unused table, NA
> improvement(permissions): remove the unused workspace_member table in favor of permissions

- apps/sim/app/chat/[subdomain]/components/voice-interface/voice-interface.tsx
- apps/sim/db/migrations/0054_naive_raider.sql
- apps/sim/db/migrations/meta/0054_snapshot.json
- apps/sim/db/migrations/meta/_journal.json
- apps/sim/db/schema.ts
- apps/sim/executor/routing/routing.test.ts
- apps/sim/executor/routing/routing.ts
- apps/sim/executor/tests/parallel-activation-integration.test.ts
- apps/sim/executor/tests/parallel-activation-regression.test.ts
- fix(subflows): fixed subflows not executing ([pr](https://github.com/simstudioai/sim/commit/61deb02959ef4b07f514e1b2781547e172558bbf))
- improvement(permissions): remove the unused workspace_member table in favor of permissions ([pr](https://github.com/simstudioai/sim/commit/e142753d642ed6f2267c067076286449d1684838))
> v0.3.3: fix + improvement

- apps/sim/app/api/users/me/settings/route.ts
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/console/components/console-entry/console-entry.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/general/general.tsx
- apps/sim/db/migrations/0055_amused_ender_wiggin.sql
- apps/sim/db/migrations/meta/0055_snapshot.json
- apps/sim/db/migrations/meta/_journal.json
- apps/sim/db/schema.ts
- apps/sim/stores/settings/general/store.ts
- apps/sim/stores/settings/general/types.ts
Added collapse setting to collapse or expand console by default. 
Select the setting to be true, then run blocks and check the console to see it's collapsed by default.
> feat(settings): collapse by default

- apps/sim/app/workspace/[workspaceId]/w/components/search-modal/search-modal.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
Fixed keyboard shortcuts to navigate.
> fix(shortcuts): fixed keyboard shortcuts

- apps/sim/app/api/chat/edit/[id]/route.test.ts
- apps/sim/app/api/chat/edit/[id]/route.ts
- apps/sim/app/api/chat/route.test.ts
- apps/sim/app/api/chat/route.ts
- apps/sim/app/api/chat/utils.test.ts
- apps/sim/app/api/chat/utils.ts
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/chat-deploy.tsx
- apps/sim/lib/urls/utils.ts
- fixed permissions to match the workspace permissions, admins can deploy & edit & delete
- fix hanging chat deploy modal on error
Tested manually, ensured that I could update & access chat.
> fix(chat-deploy): fixed permissions to match the workspace permissions, admins can deploy & edit & delete

- apps/sim/app/api/chat/[subdomain]/route.ts
- apps/sim/middleware.ts
fixed middleware logic to detect env
> fix(chat-deploy): fixed middleware logic to detect env

- apps/sim/app/api/chat/edit/[id]/route.test.ts
- apps/sim/app/api/chat/edit/[id]/route.ts
- apps/sim/app/api/chat/route.ts
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/chat-deploy.tsx
[fix(chat-deploy): fix chat deploy URL in prod (](https://github.com/simstudioai/sim/commit/e90138a6518ad4dc057cb5c61ba45ebff911a57d)https://github.com/simstudioai/sim/pull/767[)](https://github.com/simstudioai/sim/commit/e90138a6518ad4dc057cb5c61ba45ebff911a57d)
> v0.3.9: chat deploy

- apps/sim/executor/index.test.ts
- apps/sim/executor/index.ts
- apps/sim/executor/path/path.test.ts
- apps/sim/executor/path/path.ts
Tested the flow from below and ensured that it works as desired.
Handles complex routing correctly (multiple conditions/routers, many branches, subflows, etc)
> fix(condition): fixed condition block else routing bug

- apps/sim/app/api/knowledge/search/route.test.ts
- apps/sim/app/api/knowledge/search/route.ts
- apps/sim/executor/handlers/workflow/workflow-handler.ts
KBs work with workspace sharing now by using new perms system + passing workflow id in to subexecutor correctly.
Test using KB Block Search tool in a shared workspace.
> fix(kb-perms): search tool perms to use new system 

- .github/workflows/build.yml
- apps/docs/components/ui/video.tsx
- apps/docs/content/docs/blocks/evaluator.mdx
- apps/docs/content/docs/blocks/index.mdx
- apps/docs/content/docs/blocks/router.mdx
- apps/docs/content/docs/connections/index.mdx
- apps/docs/content/docs/connections/tags.mdx
- apps/docs/content/docs/execution/basics.mdx
- apps/docs/content/docs/getting-started/index.mdx
- apps/docs/content/docs/triggers/webhook.mdx
- apps/docs/content/docs/variables/index.mdx
- apps/docs/lib/utils.ts
- docker/app.Dockerfile
- feat: implement native ARM64 Docker builds with CDN support
> v0.3.11: arm64 runner, CDN video support

- apps/docs/content/docs/blocks/agent.mdx
- apps/docs/content/docs/connections/data-structure.mdx
- apps/sim/providers/models.ts
added gpt-5, gpt-5-chat, gpt-5-mini, and gpt-5-nano
NA
> feat(gpt-5): added gpt-5 models

- apps/sim/providers/models.ts
- apps/sim/stores/operation-queue/store.ts
> fix(gpt-5): remove temp, decr socket debounce to 25ms

- apps/sim/db/migrations/0069_lonely_spirit.sql
- apps/sim/db/migrations/meta/0069_snapshot.json
- apps/sim/db/migrations/meta/_journal.json
- apps/sim/db/schema.ts
added trigger-mode to workflow_blocks table, going to be followed-up wiht a PR that actually uses this field but separated it for separation of concerns
NA
> feat(trigger-mode): added trigger-mode to workflow_blocks table

- helm/sim/templates/deployment-app.yaml
- helm/sim/values.yaml
fix helm charts migrations using wrong image
N/A
> fix(helm): fix helm charts migrations using wrong image

- apps/sim/components/ui/tag-dropdown.tsx
> improvement(tag-dropdown): typed tag dropdown values

- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
fix small ui bug to close gap when creating new workflow
> fix(sidebar-ui): fix small ui bug to close gap when creating new workflow

- apps/sim/tools/http/request.ts
- apps/sim/tools/index.ts
> fix(api): fix api block

- apps/sim/tools/http/request.ts
- apps/sim/tools/index.ts
[fix(api): fix api block (](https://github.com/simstudioai/sim/commit/8016af60f489337066a1f4f63e28cc61cc108260)https://github.com/simstudioai/sim/pull/951[)](https://github.com/simstudioai/sim/commit/8016af60f489337066a1f4f63e28cc61cc108260)
> v0.3.24: api block fixes

- helm/sim/templates/external-db-secret.yaml
added template for external db secret
> improvement(helm): added template for external db secret

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/subflows/components/iteration-badges/iteration-badges.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/code.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/combobox.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/short-input.tsx
Revert all changes except to tag dropdown.
Fixes #(issue)
Manually
> fix(debounce-logic-changes): make tag dropdown fix targetted

- apps/sim/middleware.ts
fixed chat-deploy for non-hosted environments
> fix(chat-deploy): fixed chat-deploy

- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/settings-navigation/settings-navigation.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/settings-modal.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
- apps/sim/lib/environment.ts
clear separation between server-side and client-side billing envvar
Manually.
> fix(envvar): clear separation between server-side and client-side billing envvar

- apps/sim/app/api/files/utils.ts
- apps/sim/app/api/help/route.ts
- apps/sim/app/workspace/[workspaceId]/knowledge/[id]/base.tsx
- apps/sim/app/workspace/[workspaceId]/knowledge/[id]/components/upload-modal/upload-modal.tsx
- apps/sim/app/workspace/[workspaceId]/knowledge/components/create-modal/create-modal.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/help-modal/help-modal.tsx
- apps/sim/lib/auth.ts
- apps/sim/lib/email/validation.test.ts
fixed upload files modal, processing ui to match the rest of the kb and the create knowledge base modal. Made form unsubmittable unless all the name is provided.
https://github.com/user-attachments/assets/f785c099-f8eb-4b9e-95d9-8a600cc05131
> fix(kb-ui): fixed upload files modal ui, processing ui to match the rest of the kb

- apps/sim/app/api/copilot/chat/route.ts
Fixes copilot abort error
Manual
> fix(copilot): abort

- apps/sim/app/workspace/[workspaceId]/logs/components/sidebar/sidebar.tsx
- apps/sim/app/workspace/[workspaceId]/logs/logs.tsx
Remove message field from logs sidebar and fix race condition for quick fetches.
Manually
> fix(logs-sidebar): remove message and fix race condition for quickly switching b/w logs

- apps/sim/lib/logs/console/logger.ts
restore server-side logs in prod, keep client-side logs hidden
> improvement(logger): restore server-side logs in prod

- apps/docs/content/docs/tools/supabase.mdx
- apps/sim/blocks/blocks/supabase.ts
- apps/sim/tools/registry.ts
- apps/sim/tools/supabase/index.ts
- apps/sim/tools/supabase/types.ts
- apps/sim/tools/supabase/upsert.ts
add supabase upsert tool, insert/replace on PK conflict
Tested manually with a new record and with a conflict.
> improvement(supabase): add supabase upsert tool, insert/replace on PK conflict

- README.md
- apps/docs/content/docs/copilot/index.mdx
- apps/sim/next.config.ts
> feat(copilot-docs): update readme and docs with local hosting instructions

- apps/sim/.env.example
- apps/sim/app/api/help/route.ts
- apps/sim/app/api/workspaces/invitations/route.ts
- apps/sim/components/emails/base-styles.ts
- apps/sim/components/emails/batch-invitation-email.tsx
- apps/sim/components/emails/help-confirmation-email.tsx
- apps/sim/components/emails/index.ts
- apps/sim/components/emails/render-email.ts
- apps/sim/lib/auth.ts
- apps/sim/lib/email/mailer.test.ts
- apps/sim/lib/email/mailer.ts
- apps/sim/lib/env.ts
- apps/sim/package.json
- bun.lock
consolidated all emailing to mailer service, added support for Azure ACS. this way, we can also add support for AWS SES directly via the mailer without updating code anywhere else.
Tested manually with ACS.
> feat(mailer): consolidated all emailing to mailer service, added support for Azure ACS

- apps/sim/blocks/blocks/agent.ts
- apps/sim/providers/azure-openai/index.ts
- apps/sim/providers/models.ts
- apps/sim/providers/openai/index.ts
- apps/sim/providers/types.ts
- apps/sim/providers/utils.test.ts
- apps/sim/providers/utils.ts
added reasoning level and verbosity to gpt-5 models
Unit tests, tested manually to ensure that gpt-5 sends these params but other models don't
> improvement(gpt-5): added reasoning level and verbosity to gpt-5 models

- apps/sim/lib/auth.ts
- apps/sim/lib/billing/core/billing.ts
- apps/sim/lib/billing/core/organization-billing.ts
- apps/sim/lib/billing/team-management.ts
- apps/sim/lib/billing/validation/seat-management.ts
fix team plan upgrade, there were some nuances with the referenceId not being set to the org id
> fix(billing): fix team plan upgrade

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/starter/input-format.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/sub-block.tsx
- apps/sim/blocks/blocks/starter.ts
- apps/sim/executor/index.ts
Can test specific input formats during manual executions by using value field. 
https://github.com/user-attachments/assets/4cbb45d6-448e-482e-a898-2497a91670f5
> feat(input-format): add value field to test input formats

- .github/workflows/trigger-deploy.yml
Run trigger deploy to staging and prod correctly.
Must test manually.
> improvement(gh-action): add gh action to deploy to correct environment for trigger.dev

- apps/sim/next.config.ts
- apps/sim/package.json
- bun.lock
upgrade nextjs to 15.5
Tested build manually
> feat(nextjs): upgrade nextjs to 15.5

- apps/sim/app/api/tools/jira/issue/route.ts
- apps/sim/app/api/tools/jira/issues/route.ts
- apps/sim/app/api/tools/jira/projects/route.ts
- apps/sim/app/api/tools/jira/update/route.ts
- apps/sim/app/api/tools/jira/write/route.ts
- apps/sim/app/api/webhooks/poll/gmail/route.ts
- apps/sim/app/api/webhooks/poll/outlook/route.ts
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/jira-issue-selector.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/components/providers/gmail.tsx
- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/components/providers/outlook.tsx
- apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/create-menu/create-menu.tsx
- apps/sim/lib/webhooks/gmail-polling-service.ts
- apps/sim/lib/webhooks/outlook-polling-service.ts
- apps/sim/tools/airtable/get_record.ts
> fix(semantics): fix incorrect import

- apps/sim/providers/azure-openai/index.ts
- apps/sim/providers/openai/index.ts
> fix(gpt-5): fix chat-completions api

- apps/docs/content/docs/tools/microsoft_excel.mdx
- apps/sim/blocks/blocks/starter.ts
fix starter block placeholder
Manually.
> fix(placeholder): fix starter block placeholder

- .github/workflows/build.yml
- bun.lock
Brief description of what this PR does and why.
Fixes #(issue)
How has this been tested? What should reviewers focus on?
> fix(build): clear docker build cache to use correct Next.js version

- apps/sim/app/api/workspaces/invitations/route.ts
- apps/sim/lib/email/mailer.test.ts
- apps/sim/lib/email/mailer.ts
- bun.lock
remove unused param
No functional changes.
> fix(emails): remove unused useCustomFromFormat param

- apps/sim/app/manifest.ts
- apps/sim/components/emails/render-email.ts
fixed email subjects to use provided brand name
> improvement(emails): fixed email subjects to use provided brand name

- apps/sim/stores/workflows/workflow/store.test.ts
- apps/sim/stores/workflows/workflow/store.ts
- apps/sim/stores/workflows/workflow/types.ts
prevent identical normalized block names
Added unit tests, tested manually.
> fix(naming): prevent identical normalized block names

- .github/workflows/ci.yml
- apps/sim/drizzle.config.ts
- apps/sim/lib/env.ts
Brief description of what this PR does and why.
Fixes #(issue)
How has this been tested? What should reviewers focus on?
> fix(ssl): add envvar for optional ssl cert (#1179)

- apps/sim/drizzle.config.ts
> fix(db): accept self-signed certs

- apps/sim/drizzle.config.ts
Test separately resolving db certificate and url.
> fix(db): attempt parsing cert and db url separately

- .github/workflows/ci.yml
- apps/sim/drizzle.config.ts
- apps/sim/lib/env.ts
revert changes related to db URL
NA
> fix(database): revert changes related to db URL

- .devcontainer/docker-compose.yml
- .github/workflows/ci.yml
- apps/sim/drizzle.config.ts
- apps/sim/lib/env.ts
- docker-compose.local.yml
- docker-compose.ollama.yml
- docker-compose.prod.yml
fix(db): attempt parsing cert and db url separately (#1183)
> v0.3.40: drizzle fixes, custom postgres port support

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx
- apps/sim/app/workspace/[workspaceId]/w/page.tsx
- apps/sim/stores/workflows/registry/store.ts
Sidebar and Workflow stores competing to set active workflow leading to occasional race condition. Remove hacky timeout. 
Manually
> fix(race-condition-workflow-switching): another race condition between registry and workflow stores

- apps/sim/app/api/webhooks/trigger/[path]/route.ts
Skip webhook queue for enterprise plan users. 
Manually
> feat(enterprise-plan-webhooks): skip webhook queue for enterprise plan users

- apps/sim/app/api/webhooks/trigger/[path]/route.ts
Revert bypass of trigger dev. 
Manually.
> Revert "feat(enterprise-plan-webhooks): skip webhook queue for enterprise plan users 

- apps/sim/app/api/schedules/execute/route.ts
- apps/sim/app/api/webhooks/trigger/[path]/route.ts
- apps/sim/app/api/workflows/[id]/execute/route.ts
Revert trigger dev bypass for enterprise users since db calls are taking too long.
> 0.3.48: revert trigger dev bypass for enterprise users

- bun.lock
> chore(bun-lock): regenerate bun.lock

- apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx
Fix cursor misalignment in long text inputs by ensuring textarea and overlay have matching font sizes, borders, and scrollbar behavior
Any long system prompt in the agent block that enables the scroll bar
> fix(cursor): misaligned in long inputs

- apps/sim/package.json
- bun.lock
Brief description of what this PR does and why.
Fixes #(issue)
How has this been tested? What should reviewers focus on?
> chore(deps): update trigger.dev sdk

- apps/sim/tools/supabase/query.ts
Fixes the order by subblock in supabase
I tested with adding ASC and DESC to the order by, and it works.
> fix(supabase): fixed supabase order by

- .github/workflows/images.yml
Fix docker maniest ci sha prefix
Fixes #(issue)
n/a
> fix(ci): fix docker manifest

- .github/workflows/trigger-deploy.yml
> fix(ci): add skip promotion to trigger ci

- apps/sim/lib/copilot/tools/client/examples/get-operations-examples.ts
- apps/sim/lib/copilot/tools/client/other/plan.ts
> fix(copilot): tool renaming
