.github/PULL_REQUEST_TEMPLATE.md, package-lock.json, package.json, sim/app/api/webhooks/test/route.ts, sim/app/api/webhooks/trigger/[path]/route.ts, sim/app/blocks/blocks/starter.ts, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/webhook-config.tsx
Added support for generic webhooks.
Fixes #112 
- [y] New feature (non-breaking change which adds functionality)
I configured a generic webhook, and ran the test to confirm it worked. Then, I took the cURL that it generated and ran it in my terminal and I was able to trigger my workflow.
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] My changes generate no new warnings
- [y] I have added tests that prove my fix is effective or that my feature works
- [y] Any dependent changes have been merged and published in downstream modules
- [y] I have updated version numbers as needed (if needed)
- [y] My changes …
=> feat[webhook]: added generic webhook

sim/app/(landing)/github-stars.tsx, sim/app/(landing)/landing.tsx, sim/app/(landing)/nav-client.tsx
Instead of hard coding the number of GitHub stars, this uses the GitHub api to fetch the count. This required turning the landing page into a server component and separate the client-facing parts into their own client component. 
- [y] Code refactoring (no functional changes)
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] My changes generate no new warnings
- [y] My changes do not introduce any new security vulnerabilities
- [y] I have …
=> refactor[landing]: use github api to fetch stars instead of hardcoding

sim/app/blocks/blocks/starter.ts, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/providers/discord-config.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/ui/webhook-header.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/webhook-config.tsx
added discord webhook
Fixes #114 
=> feat[webhook]: added discord webhook

sim/app/api/db/workflow/route.ts, sim/app/api/schedules/execute/route.ts, sim/app/api/schedules/route.ts, sim/app/api/user/stats/route.ts, sim/app/api/webhooks/trigger/[path]/route.ts, sim/app/api/workflows/[id]/deploy/route.ts, sim/app/api/workflows/[id]/execute/route.ts, sim/app/api/workflows/[id]/stats/route.ts, sim/app/api/workflows/middleware.ts, sim/app/w/[id]/components/control-bar/control-bar.tsx, sim/db/migrations/0021_shocking_korath.sql, sim/db/migrations/meta/0021_snapshot.json, sim/db/migrations/meta/_journal.json, sim/db/schema.ts, sim/lib/logs/execution-logger.ts, sim/lib/workflows.ts, sim/lib/workflows/utils.ts, sim/stores/workflows/middleware.ts
- **ran migrations for new table, fixed build issue. added a user/stats route  to fetch all user stats for the dashboard we'll eventually create**
- **added user_stats table to track total number of workflow runs**
- **added metrics for different types of triggers and runs**
- **add total_tokens_used and total_cost metrics**
In this PR, we added a user_stats table to postgres that includes information about totalWorkflowRuns, totalApiCalls, totalWebhookTriggers, totalScheduledExecutions, totalTokensUsed, totalCost, workflowsCreated, lastActive. This information will help inform us on how much each of the triggers is being used, as well as see the power users by tracking how many executions they've ran. Also, when we launch we'll need to limit the number of executions for free users, and …
=> feat(metrics): add user_stats table that tracks more granular usage information per user

sim/app/globals.css, sim/app/w/[id]/components/panel/components/console/components/console-entry/console-entry.tsx, sim/app/w/[id]/components/workflow-block/components/connection-blocks/connection-blocks.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/credential-selector/components/oauth-required-modal.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/credential-selector/credential-selector.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/long-input.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/short-input.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/table.tsx, sim/app/w/[id]/components/workflow-block/workflow-block.tsx, sim/app/w/[id]/hooks/use-workflow-execution.ts, sim/app/w/[id]/workflow.tsx, sim/app/w/components/sidebar/components/settings-modal/components/credentials/credentials.tsx, sim/app/w/marketplace/components/toolbar/toolbar.tsx, sim/app/w/marketplace/marketplace.tsx, sim/blocks/blocks/x.ts, sim/executor/index.ts, sim/executor/path.ts, sim/executor/types.ts, sim/lib/auth.ts, sim/package-lock.json, sim/stores/panel/variables/store.ts, sim/tools/x/read.ts, sim/tools/x/search.ts, sim/tools/x/types.ts, sim/tools/x/user.ts, sim/tools/x/write.ts
- **added x oauth**
- **added x oauth to x tools**
- **added supabase oauth**
- **ui improvements for action required banner in settings > credentials**
- **improvement(oauth): if there is already an account connected, don't display the connect button in the credential selector**
- **fixed typo in marketplace for customer_service**
- Added X OAuth, updated blocks to use OAuth credential selector and tools to use credentials instead of API keys
- Added Supabase OAuth
- Fixed bug where we fetch credentials repeatedly while credential dropdown is open, only fetch on mount 
- UI improvements for Settings > Credentials
- Fixed typo in marketplace
Fixes #98 
Authenticated with X, ran the X block. Authenticated with Supabase.
=> feat(oauth): general oauth improvements, added x and supabase oauth

sim/blocks/blocks/mistral-parse.ts, sim/blocks/index.ts, sim/components/icons.tsx, sim/tools/index.ts, sim/tools/mistral/index.ts, sim/tools/mistral/parser.ts
Created a Mistral block with a parse tool to parse PDFs. 
Ran a pdf through with my own API key and it worked (must have PDF link). 
Still need to add the ability to manually upload files to test OCR with local file upload (or hosted file upload).
=> feat(mistral-OCR): added mistral tool and block for parsing pdfs

sim/app/api/codegen/route.ts, sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/components/custom-tool-modal/custom-tool-modal.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx, sim/blocks/blocks/agent.test.ts, sim/blocks/blocks/agent.ts, sim/components/ui/toggle.tsx, sim/executor/handlers/agent/agent-handler.test.ts, sim/executor/handlers/agent/agent-handler.ts, sim/hooks/use-code-generation.ts, sim/package-lock.json, sim/package.json, sim/providers/anthropic/index.ts, sim/providers/cerebras/index.ts, sim/providers/deepseek/index.ts, sim/providers/google/index.ts, sim/providers/groq/index.ts, sim/providers/model-capabilities.test.ts, sim/providers/model-capabilities.ts, sim/providers/ollama/index.ts, sim/providers/openai/index.ts, sim/providers/types.ts, sim/providers/utils.ts, sim/providers/xai/index.ts
- **added tool usage config to agents' tools, some more things to do**
- **allow sequential forcing of multiple tools for providers that support it**
- **remove google from the list of providers with granular tool usage control**
- **conditionally render tool usage icons if the model supports it**
- **fixed styles and added unit tests**
Added granular tool usage control for the model providers that support it. Sometimes, users want to force a tool call every time an agent is called, and this allows them that granular control. If they choose not to modify it, it is on auto like it was before and there is no change. This was only added for model providers that support it.
I tested this manually for openai, anthropic, and deepseek models which are the providers that allow this type of …
=> feat(agent): added granular tool usage control for the model providers that support it

sim/app/w/[id]/components/workflow-block/components/sub-block/hooks/use-sub-block-value.ts, sim/blocks/blocks/router.ts, sim/executor/handlers/evaluator/evaluator-handler.test.ts, sim/executor/handlers/evaluator/evaluator-handler.ts, sim/executor/handlers/router/router-handler.test.ts, sim/executor/handlers/router/router-handler.ts
Fixed router and evaluator block, added autofill & tests. Now all provider blocks (evalautor, router, agent) all execute server-side and have autofill based on the model provider selected in the dropdown.
Tested a huge workflow manually with evaluator, router, & agent block
=> fix(blocks): fixed router and evaluator block, added autofill & tests

sim/blocks/blocks/api.ts, sim/tools/http/request.test.ts, sim/tools/http/request.ts
add default headers for API requests (best practice)
Cannot be tested locally since API's do not accept requests from insecure origins. but resolved CORS issue which was due to default headers not being set.
=> improvement(api): add default headers for API requests, user can override

sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx, sim/tools/firecrawl/scrape.ts, sim/tools/slack/message.ts, sim/tools/types.ts, sim/tools/utils.ts
Tool inputs can now accept optional tool parameters
Force a tool call with no system prompt and user prompt and add some text into Firecrawl URL in tool input. So far, I only added Slack and Firecrawl optional params.
=> feat(optional-tool-input): added ability to add optional params

sim/middleware.ts, sim/next.config.ts
Added additional security measures to next config & middleware after DAST scan.
Ran the workflow manually, via API, & via schedule to confirm that the additional headers & security measures don't impact real users.
=> feat(security): added additional security measures to next config & middleware

sim/app/w/[id]/components/control-bar/components/deploy-modal/components/chat-deploy/chat-deploy.tsx, sim/app/w/[id]/components/control-bar/components/deploy-modal/deploy-modal.tsx, sim/app/w/components/sidebar/components/settings-modal/components/credentials/credentials.tsx, sim/tools/x/read.ts, sim/tools/x/search.ts, sim/tools/x/write.ts
Fixed hanging deployment state, fixed x tools, fixed credentials styling
Tested manually, deploying the workflow and confirming that everything works as expected.
=> fix(chat-deploy): fixed hanging deployment state, fixed x tools, fixed credentials styling

sim/providers/ollama/index.ts
Fix for using local ollama instance running on host via host.docker.internal mapping.  Currently hardcoded to localhost which results in ECONNREFUSED.  
Tested using docker compose with host mapping:
```
extra_hosts:
- "host.docker.internal:host-gateway"
environment:
- OLLAMA_HOST=http://host.docker.internal:11434
```
- [x ] My changes generate no new warnings
Any additional information, configuration or data that might be necessary to reproduce the issue or …
=> fix(ollama): set OLLAMA_HOST from env variable

sim/app/api/auth/oauth/jira/issue/route.ts, sim/app/w/[id]/components/workflow-block/components/sub-block/components/file-selector/components/jira-issue-selector.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/components/file-selector/file-selector-input.tsx
Jira project and issues weren't remaining selected after the page refreshed or the workflow changed. Added logic to keep the issues and projects persisting. I also added matching logs that are in the project picker for the issue picker.
Refreshed the page after selecting a project and issue to make sure they remained selected.
=> jira project and issue auto loading

sim/app/w/[id]/components/workflow-block/components/sub-block/components/long-input.tsx, sim/app/w/[id]/components/workflow-block/components/sub-block/sub-block.tsx, sim/blocks/blocks/agent.ts, sim/blocks/types.ts
Fixed the text overlay and resize UI. Previously, on long messages in the system prompt 
=> fix(long-input): text overlay and resize UI

apps/sim/app/api/workflows/[id]/status/route.ts, apps/sim/app/globals.css, apps/sim/app/w/[id]/components/control-bar/control-bar.tsx, apps/sim/app/w/[id]/components/toolbar/toolbar.tsx, apps/sim/app/w/[id]/workflow.tsx, apps/sim/app/w/components/sidebar/components/sidebar-control/sidebar-control.tsx, apps/sim/app/w/components/sidebar/components/workspace-header/workspace-header.tsx, apps/sim/app/w/components/sidebar/sidebar.tsx, apps/sim/app/w/logs/logs.tsx, apps/sim/lib/usage-monitor.ts, apps/sim/stores/sidebar/store.ts
Extended sidebar capability to expand on hover in addition to expand/collapse. 
Open/close toolbar, workflow, and logs. Set different sidebar controls and test out each page.
=> feat(sidebar-controls): added ability to expand on hover

apps/sim/app/api/workspaces/invitations/route.ts, apps/sim/app/w/components/sidebar/components/invite-modal/invite-modal.tsx, apps/sim/app/w/components/sidebar/components/invite-modal/invites-sent/invites-sent.tsx, apps/sim/app/w/components/sidebar/sidebar.tsx
Allow anyone with access to the workspace to invite others, remove invite from dev environment
=> fix(invite): allow anyone with access to the workspace to invite others, remove invite from dev environment

apps/sim/app/api/schedules/execute/route.ts, apps/sim/app/api/workflows/[id]/execute/route.ts
Fix async executions when envvars are not set. We were previously mandating that the user have envvars set, but sometimes a user will have a workflow that does not rely on envvars and we should allow them to execute asynchronously.
Tested manually to ensure that we could execute just fine without any envvars set.
=> fix(executions): fix async executions when envvars are not set

apps/sim/app/w/[id]/components/control-bar/components/deploy-modal/deploy-modal.tsx, apps/sim/app/w/[id]/components/control-bar/components/deployment-controls/components/deployed-workflow-card.tsx, apps/sim/app/w/[id]/components/control-bar/components/deployment-controls/components/deployed-workflow-modal.tsx, apps/sim/app/w/[id]/components/control-bar/components/deployment-controls/deployment-controls.tsx, apps/sim/app/w/[id]/components/control-bar/control-bar.tsx, apps/sim/app/w/[id]/components/notifications/notifications.tsx, apps/sim/app/w/[id]/hooks/use-deployment-change-detection.ts, apps/sim/stores/workflows/index.ts, apps/sim/stores/workflows/registry/store.ts, apps/sim/stores/workflows/registry/types.ts, apps/sim/stores/workflows/workflow/store.ts, apps/sim/stores/workflows/workflow/types.ts
Workflows were rendering as deployed when creating new ones, and the deployed state across workflows was getting mixed up. Added rechecks on reverted changes, handling both true/false API responses, enabling subblock change detection, adding 5s polling to auto-clear state, and cleaning up code to resolve race conditions.
Deploying new workflows, modifying existing workflows, and navigating between different workflows to observe changes in deployment status. Made sure indicator accurately reflected the current state, correctly detected changes, and reliably cleared when workflows were reverted—all without requiring a page refresh.
=> fix(deployed-workflow): fixed the deployment status changes across workflows.

apps/sim/app/chat/[subdomain]/chat-client.tsx, apps/sim/app/chat/[subdomain]/components/auth/email/email-auth.tsx, apps/sim/app/chat/[subdomain]/components/auth/password/password-auth.tsx, apps/sim/app/chat/[subdomain]/components/message-container/message-container.tsx, apps/sim/app/chat/[subdomain]/components/message/components/markdown-renderer.tsx, apps/sim/app/chat/[subdomain]/components/message/message.tsx
Optimized chat performance & pass/email flow for chat
Tested chat manually to ensure nothing changed. We memoize expensive calculations on old messages in the messages array, so we don't recompute the format of all the prior messages on each new incoming message.
=> improvement(chat): optimized chat performance & pass/email flow for chat

apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/file-selector/components/teams-message-selector.tsx, apps/sim/tools/microsoft_teams/attachment-utils.ts, apps/sim/tools/microsoft_teams/read_channel.ts, apps/sim/tools/microsoft_teams/read_chat.ts, apps/sim/tools/microsoft_teams/types.ts, apps/sim/tools/microsoft_teams/write_channel.ts
Added support for teams attachments.
Ran the tools and saw the attachments there.
=> feat(teams-attachments): added support for teams attachments

apps/sim/app/w/logs/components/trace-spans/trace-spans-display.tsx
Fixed styling issues in the logs panel where the timeline visualisation would slide off the page during panel resizing/closing operations.
Tested by opening/closing logs panel, browser window resizing, and confirmed timeline stays visible and properly sized.
Before:
https://github.com/user-attachments/assets/8b8eec7e-7550-4160-9754-e034e415e0bd
After:
https://github.com/user-attachments/assets/570cd8d9-98e4-43b2-9bd3-a6383fe8505a
=> fix(logs): improve timeline resizing behavior in trace spans

apps/sim/app/w/[id]/components/loop-node/loop-node.test.tsx, apps/sim/app/w/[id]/components/loop-node/loop-node.tsx, apps/sim/app/w/[id]/components/parallel-node/parallel-node.test.tsx, apps/sim/app/w/[id]/components/parallel-node/parallel-node.tsx, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/app/w/[id]/components/workflow-block/workflow-block.tsx, apps/sim/app/w/[id]/utils.ts, apps/sim/app/w/[id]/workflow.tsx
Fixed UI issues with resizing the node, dragging content into the node, and auto connecting the nodes.
Confirmed that each change I made worked on both the parallel and loop nodes. I also wrote two test files.
=> fit(loop-ui): fixed some UI issues, added tests for parallel and loop nodes

apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/code.tsx
Persist collapsed state for responseFormat code subblock. On a block-level, we persist the horizontal handles, wide, etc. For the sub-block level, we did not persist when we collapsed the sub-block, and therefore every time we refresh it would re-initialize as expanded, causing a bad UX.
Tested manually by collapsing the sub-block state and refreshing, ensuring it persisted in the state/store.
=> fix(persistence): persist collapsed state for responseFormat code subblock

apps/sim/app/api/help/route.ts, apps/sim/app/api/workspaces/invitations/route.ts, apps/sim/lib/auth.ts, apps/sim/lib/env.ts, apps/sim/lib/mailer.ts
Add customizable `FROM` email with next public app url so users can use their own verified domains to send emails
Fixes #446 
Tested and confirmed that we can still send emails manually.
=> feat(email): add customizable "FROM" email for resend

.devcontainer/docker-compose.yml, apps/sim/db/migrations/0000_careless_black_knight.sql, apps/sim/db/migrations/0006_plain_zzzax.sql, bun.lock, docker-compose.local.yml, docker-compose.prod.yml, docker/db.Dockerfile, packages/simstudio/package.json, packages/simstudio/src/index.ts
We recently added pgvector and the vector type to the db, and postgres does not natively support this type. As such, we needed to add pgvector image to docker builds, modified push to migrate to ameliorate vector data type issue
Fixes #450 
Tested with `docker-compose -f docker-compose.local.yml up migrations db` to confirm that the vector issue was resolved and that it built the migrations image successfully.
=> fix(docker): added pgvector image to docker builds, modified push to migrate to ameliorate vector data type issue

apps/sim/providers/xai/index.ts
There is a known issue where XAI cannot handle tool calls + response format when used together. We fixed this by only asking for a json_schema (formatted response) on the last call before xai responds.
Tested manually with xai with no tool calls and no response format, tool calls with no response format, response format with no tool calls, and then both. All worked + confirmed forcing functionality and streaming work.
=> fix(providers): fixed xai response format + tool calls not working when used together

apps/docs/content/docs/tools/firecrawl.mdx, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx, apps/sim/blocks/blocks/firecrawl.ts, apps/sim/tools/firecrawl/index.ts, apps/sim/tools/firecrawl/search.ts, apps/sim/tools/firecrawl/types.ts, apps/sim/tools/registry.ts, bun.lock, package.json
- Added new firecrawl search endpoint
- For optional inputs, we were rendering them in the tool input regardless of what operation was selected. Instead, we add conditional sub-block rendering the same way it is rendered for the blocks
Tested manually, ensured that we have backwards compatibility since scrape is selected by default in operations and the scrape params all stay the same.
=> feat(tools): add firecrawl search, add conditional sub-block rendering to tool input for agents

apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/file-selector/file-selector-input.tsx
Resolved issue that attempted to pull google calendar info for docs and sheets tools.
Fixes #460 
Verified that google docs and sheets pulled from google drive. Verified that google calendar was also working properly.
=> fix(gcal): fixed bug that pulled google calendar info

apps/sim/middleware.ts
The User-Agent header header that Telegram includes when it sends a webhook request is an empty user-agent. While we set the user-agent when sending requests to Telegram to be 'TelegramBot/1.0', Telegram always sends back an empty user-agent for a webhook request which causes middleware to block a Telegram webhook request.
Commented out
`// Skip waitlist protection for development environment
if (isDevelopment) {
return NextResponse.next()
}`
to replicate the production server in order to replicate the blockage I was running into. Added these changes with isDevelopment still commented out, confirmed I was able to pass the middleware checks, then uncommented out isDevelopment.
=> fix(telegram-middleware): modified middleware to not check for user-agent on webhook

apps/sim/app/w/[id]/components/loop-node/loop-node.tsx, apps/sim/app/w/[id]/components/parallel-node/parallel-config.ts, apps/sim/app/w/[id]/components/parallel-node/parallel-node.tsx, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/code.tsx, apps/sim/app/w/knowledge/[id]/[documentId]/document.tsx, apps/sim/app/w/knowledge/[id]/base.tsx, apps/sim/app/w/knowledge/knowledge.tsx, apps/sim/hooks/use-knowledge.ts, apps/sim/stores/knowledge/store.ts
Added pagination to a knowledge base as well as other minor design changes (colors and collapsable feature for code)
Verified that the pages were navigable and showed all of the chunks in a knowledge base.
=> fix(knowledge-ux): fixed ux for knowledge base

apps/sim/app/w/[id]/workflow.tsx, apps/sim/hooks/use-tab-sync.ts
Relatively hacky timestamp-based conflict resolution. Movement syncs were buggy so made it a structural sync [only adding/removing blocks, edges and changes to subblocks]. Have a boolean flag to prevent multiple syncs from running simultaneously.
Prevents sync conflicts with 2s intervals and mutex locks. 
Preserves position but merges other changes. 
=> fix(tab-sync): sync between tabs on change 

apps/sim/app/w/knowledge/components/create-modal/components/create-form/create-form.tsx
Upload presigned url to kb for file upload instead of the whole file, circumvents 4.5MB serverless func limit
Tested file upload to ensure that we can upload larger files, up to 100MB
=> fix(file-upload): upload presigned url to kb for file upload instead of the whole file, circumvents 4.5MB serverless func limit

apps/sim/app/api/function/execute/route.test.ts, apps/sim/app/api/function/execute/route.ts, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/providers/gmail.tsx, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx, apps/sim/app/w/[id]/components/workflow-block/components/sub-block/components/webhook/webhook.tsx, apps/sim/lib/webhooks/gmail-polling-service.ts, apps/sim/lib/webhooks/utils.ts
Added option to grab raw gmail from gmail polling service. When the user is configuring the webhook, they now have the option to get the entire incoming email object. This enables more complex usecases where the user may need headers, base64 encoding, etc
Tested locally to ensure that we were able to get the simple email object and the raw email object both. Added a ton of unit tests
=> feat(gmail): added option to access raw gmail from gmail polling service

apps/sim/app/api/__test-utils__/utils.ts, apps/sim/app/api/folders/[id]/route.test.ts, apps/sim/app/api/folders/[id]/route.ts, apps/sim/app/api/folders/route.test.ts, apps/sim/app/w/components/sidebar/components/folder-tree/components/folder-item.tsx, apps/sim/lib/variables/variable-manager.ts, apps/sim/stores/folders/store.ts, apps/sim/stores/workflows/registry/store.ts, biome.json
modified folder deletion to delete subfolders & workflows in it instead of moving to root, more intuitive for user as long as delete message is clear
Tested deleted a subfolder, all of its contents were deleted. Also tested deleting a folder with subfolders & workflows, also confirmed it deleted successfully.
=> fix(folders): modified folder deletion to delete subfolders & workflows in it instead of moving to root

apps/sim/components/ui/tag-dropdown.test.tsx, apps/sim/components/ui/tag-dropdown.tsx
Fixed extra closing tag on tag dropdown autocomplete
Fixes #509 
Added unit tests to test regex logic, ensured that we are not adding an extra closing tag irregardless of the cursor position.
=> fix(autocomplete): fixed extra closing tag on tag dropdown autocomplete

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/utils.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx
=> fix(autolayout): fixed autolayout with sockets

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx
Fixes the issue where API calls are being made to `undefined` workspace id because it's trying to get `workspaceId` from workflows which are loading or haven't loaded yet.
=> fix: workspace undefined

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, .github/workflows/build.yml, README.md, apps/sim/package.json, docker-compose.local.yml, docker-compose.prod.yml, docker/realtime.Dockerfile, package.json, packages/cli/src/index.ts
Note: The image is highly unoptimized because it's all packaged within the same app in our mono-repo, this will gradually become a lot more lightweight once we properly utilise the mono-repo.
Locally built and ran.
=> ci: socket realtime image for hosting

apps/sim/app/api/workflows/sync/route.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-header/workspace-header.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx, apps/sim/app/workspace/[workspaceId]/w/page.tsx, apps/sim/contexts/socket-context.tsx, apps/sim/stores/workflows/registry/store.ts
=> Revert "fix(workspace url id bug): switch workspace bug "

packages/cli/package.json, packages/cli/src/index.ts
Prepare CLI for publishing. We can change `migrate` back to `push` once its fixed. Currently seeing the following error:
```bash
$ bunx drizzle-kit push
No config path provided, using default 'drizzle.config.ts'
Reading config file '/app/apps/sim/drizzle.config.ts'
Using 'postgres' driver for database querying
[⣷] Pulling schema from database...
[✓] Pulling schema from database...
790 |     }
791 |   )
792 |   Error.captureStackTrace(error, notSupported)
793 |   return error
794 | }
^
PostgresError: type "vector" does not exist
severity_local: "ERROR",
severity: "ERROR",
position: "297",
file: "parse_type.c",
routine: "typenameType",
code: "42704"
at ErrorResponse (/app/node_modules/postgres/src/errors.js:794:5)
```
Ran it locally.
Any …
=> fix(cli): package type for esm imports, missing realtime

.github/workflows/ci.yml
This will run the workflow on `staging` branch which is our target for all PRs + run migrations to staging database if PRs get merged to that branch.
=> chore(ci): run ci on staging + migrations

apps/sim/app/api/function/execute/route.ts
=> fix(variable resolution): use variable references to not have escaping issues

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/index.test.ts, apps/sim/socket-server/validation/schemas.ts
When you drag and drop -- it adds a block + edge. These are currently sent as separate socket events. But sometimes the edge db call finishes before the block -- and errors since target block doesn't exist yet. 
This autoEdge mode makes sure the block addition is awaited. New sockets event for this. 
Test dragging and dropping blocks onto canvas and refresh. Also add edges normally and refresh. 
=> fix(race-cond): for auto-connect rare race condition between adding edge + block

apps/sim/app/api/function/execute/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/document-selector/document-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/file-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-upload.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/knowledge-base-selector/knowledge-base-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/project-selector/project-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/index.test.ts, apps/sim/socket-server/validation/schemas.ts
- Special Subblock Selectors now use collab hooks correctly for updates 
- Race condition between edge and block addition for autoconnect fixed
=> v0.2.3: fix

apps/docs/content/docs/tools/knowledge.mdx, apps/sim/blocks/blocks/knowledge.ts, apps/sim/lib/documents/document-processor.ts, apps/sim/providers/utils.test.ts, apps/sim/tools/knowledge/create_document.ts, apps/sim/tools/knowledge/index.ts, apps/sim/tools/knowledge/types.ts, apps/sim/tools/knowledge/upload_document.ts, apps/sim/tools/registry.ts
Added tool on knowledge base to create documents to a KB.
Add one document and multiple documents at a time. Confirmed the documents uploaded properly.
=> improvement(knowledge-upload): create and upload document to KB

apps/sim/app/api/chat/utils.ts, apps/sim/app/api/schedules/execute/route.test.ts, apps/sim/app/api/schedules/execute/route.ts, apps/sim/app/api/webhooks/trigger/[path]/route.test.ts, apps/sim/app/api/webhooks/trigger/[path]/route.ts, apps/sim/app/api/workflows/[id]/deploy/route.test.ts, apps/sim/app/api/workflows/[id]/deploy/route.ts, apps/sim/app/api/workflows/[id]/execute/route.test.ts, apps/sim/app/api/workflows/[id]/execute/route.ts, apps/sim/db/schema.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts, apps/sim/lib/webhooks/utils.ts, apps/sim/stores/workflows/registry/store.ts
Update to only use normalized tables in chat, schedule, workflow in workflow, webhooks. 
Must test all the functionality listed above.
=> fix(remove workflow.state usage): no more usage of deprecated state column in any routes

apps/sim/stores/index.ts
Remove beforeunload warning since we communicate via wss. This removes the 'Are you sure you want to leave this page?' every time someone closes the simstudio tab. This is not necessary since we stream changes in realtime.
Tested navigating away from the tab, ensured there was no alert dialog.
=> fix(unload): remove beforeunload warning since we communicate via wss

apps/sim/executor/index.test.ts, apps/sim/executor/index.ts, apps/sim/executor/path.test.ts, apps/sim/executor/path.ts
- the dependency checker was incorrectly waiting for ALL incoming connections to be satisfied (including the non-selected API path), so we fixed it by checking if a source block is intentionally excluded from execution first, which automatically satisfies that dependency.
Ran the workflow pictured below and it worked, despite not having a value for one of the referenced blocks later in the execution.
=> fix(executor): fix dependency resolution, allow blocks with multiple inputs to execute

apps/sim/app/api/workspaces/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/schedule/schedule-config.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/create-menu/create-menu.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx, apps/sim/stores/workflows/registry/store.ts, apps/sim/stores/workflows/registry/utils.ts
No more client side id generation for new workflows, update scheduling deps to be correct, add loading state during creation of workflows to prevent race condition generating spams of the add button. 
Changed naming to be more fun. Added way more colors. 
Test creating workflows, creating workspaces and switching between things.
=> fix(createWorkflow): cleanup create workflow to prevent re-renders

apps/sim/app/workspace/[workspaceId]/logs/logs.tsx, apps/sim/app/workspace/[workspaceId]/w/components/workflow-preview/workflow-preview.tsx
- If you click on View Frozen Canvas for migrated logs from old system shows workflow error. This PR makes it show a warning. 
- Infinite scroll logs table was causing dynamic resizing of column headers. This also fixes that.
Click on old log that's been migrated and click on view frozen canvas -- should show warning.
=> fix(frozen canvas): don't error if workflow state not available for migrated logs

apps/sim/blocks/blocks/reddit.ts, apps/sim/lib/auth.ts, apps/sim/lib/env.ts, apps/sim/lib/oauth/oauth.test.ts, apps/sim/lib/oauth/oauth.ts, apps/sim/tools/reddit/get_comments.ts, apps/sim/tools/reddit/get_posts.ts, apps/sim/tools/reddit/hot_posts.ts, apps/sim/tools/reddit/types.ts
Update Reddit Tool to use OAuth endpoints. 
https://github.com/user-attachments/assets/f4196ed3-8e17-4d70-986f-fa2bbcbe6004
=> fix(reddit): update to oauth endpoints 

apps/docs/package.json, apps/sim/next.config.ts, apps/sim/package.json, bun.lock
Added turbopack in prod since [this page](https://areweturboyet.com) has reached 100% integration test passing, and turbopack leads to up to ~83% faster builds 
Fixes #244 
Tested to make sure everything runs fine
=> feat(build): added turbopack builds to prod

apps/sim/app/api/workflows/[id]/execute/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/response/response-format.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-block-connections.ts, apps/sim/executor/handlers/agent/agent-handler.test.ts, apps/sim/executor/handlers/agent/agent-handler.ts, apps/sim/serializer/index.ts
Agent block response format non-json format crash bug. 
https://github.com/user-attachments/assets/5f7497f1-e0a1-48cb-90d6-564630811a3b
=> fix(resp format): non-json input was crashing

apps/sim/app/api/workflows/[id]/revert-to-deployed/route.ts, apps/sim/contexts/socket-context.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/socket-server/rooms/manager.ts, apps/sim/socket-server/routes/http.ts, apps/sim/stores/workflows/workflow/store.ts
Revert to deployed state was not working correctly, and was not informing the socket server accurately. This PR fixes that.
https://github.com/user-attachments/assets/10576d6e-c8c3-4950-925f-5c3bacd2f541
=> fix(revert-deployed): correctly revert to deployed state as unit op using separate endpoint

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/connection-blocks/connection-blocks.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-block-connections.ts, apps/sim/components/ui/tag-dropdown.tsx
simplify & fix tag dropdown for parallel & loop blocks. previously, the tag dropdown did not appear for parallel or loop blocks
Tested manually to ensure that the dropdown appeared & that we can access the values properly
https://github.com/user-attachments/assets/49cca29a-9a70-4f01-96d1-66f12b695500
=> fix(dropdown): simplify & fix tag dropdown for parallel & loop blocks

apps/sim/app/api/chat/[subdomain]/route.ts, apps/sim/app/api/chat/utils.ts, apps/sim/app/chat/[subdomain]/chat-client.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/chat/chat.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/chat/components/output-select/output-select.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/console/components/console-entry/console-entry.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-workflow-execution.ts, apps/sim/components/ui/tag-dropdown.test.tsx, apps/sim/components/ui/tag-dropdown.tsx, apps/sim/executor/index.ts, apps/sim/executor/types.ts, apps/sim/executor/utils.test.ts, apps/sim/executor/utils.ts, apps/sim/lib/response-format.ts, apps/sim/lib/tokenization/streaming.ts, apps/sim/stores/panel/console/store.ts, apps/sim/stores/panel/console/types.ts
- **add response format structure to tag dropdown**
- **handle response format outputs for chat client and chat panel, implemented the response format handling for streamed responses**
Previously, we did not reflect the response format in the tag dropdown, chat panel output selector, and chat client output selector. This was due to the fundamental reason that we we did not have the setup to support structured output + streaming, but now we do. And it reflects properly in the console logs and the logs.
Tested manually, added testing.
https://github.com/user-attachments/assets/07083d4a-c0ca-4dff-8d17-688b3b464e5c
=> fix(response-format): add response format to tag dropdown, chat panel, and chat client

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/user-avatar-stack/components/connection-status/connection-status.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/user-avatar-stack/user-avatar-stack.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/control-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/toolbar/components/toolbar-block/toolbar-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/toolbar/components/toolbar-loop-block/toolbar-loop-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/toolbar/components/toolbar-parallel-block/toolbar-parallel-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/action-bar/action-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/app/workspace/[workspaceId]/w/components/providers/workspace-permissions-provider.tsx, apps/sim/contexts/socket-context.tsx
force user to refresh on disconnect in order to mkae changes, add read-only offline mode
Tested manually, ensured that when we go offline, that even when we come back online the notif persists to refresh adn that we stay in read-only mode until teh user refreshes.
-  [x] My code follows the style guidelines of this project
=> fix(sockets): force user to refresh on disconnect in order to mkae changes, add read-only offline mode

apps/sim/app/workspace/[workspaceId]/w/components/providers/workspace-permissions-provider.tsx
Only show warning after 6 seconds after disconnection.
=> fix(6s-timeout): 6 seconds timeout for sockets server warning 

apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/subscription/components/cancel-subscription.tsx
Cancel Subscription needs reference id.
=> fix(cancel-subscription): cancel subscription needs reference id

.husky/pre-commit, package.json
Previously, when we committed it would re-stage files that got changed on commit. Now, we run lint-staged to ensure that biome only runs on staged files, we automatically stage any files that biome modiifes, and we complete the commit with all the changes included.
Tested manually by creating a file that had bad formatting, staged & committed and made sure that it ranter linter on staged files & added them to commit
=> fix(precommit-hook): fixed pre commit hook to use lint-staged

apps/sim/app/workspace/[workspaceId]/knowledge/components/create-modal/create-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/eval-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/schedule/components/schedule-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/subscription/components/edit-member-limit-dialog.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/subscription/components/usage-limit-editor.tsx
Prevent save password on usage limit change
Tested manually by updating amount and ensured password manager did not appear
=> fix(text-fields): prevent save password on usage limit change

apps/sim/app/workspace/[workspaceId]/logs/components/trace-spans/trace-spans-display.tsx, apps/sim/lib/logs/trace-spans.test.ts, apps/sim/lib/logs/trace-spans.ts
Make tool calls separately collect in the trace span. And align model responses with overall duration.
https://github.com/user-attachments/assets/af4a42a4-17f6-4f03-84d7-b050d77401b5
=> improvement(trace-span): make tool calls separately collect in the tracespan 

apps/docs/app/global.css, bun.lock, package.json
remove root-level tailwind v3 override that was causing docs to not be styled locally
Tested by running `bun run dev` manually and ensuring that the dosc were styled
=> fix(docs): remove root-level tailwind v3 override

apps/sim/app/api/schedules/route.ts, apps/sim/lib/schedules/utils.test.ts, apps/sim/lib/schedules/utils.ts
Custom cron expression wasn't working. Added cronExpression field in utils.ts and fixed formatting displayed to the user.
Verified custom cron expressions were setting properly by testing with: 0 0 1 */3 *, */15 * * * *, 0 0 1 1,7 *, and 0 0 1 2-12/2 *.
=> fix(schedule): fix for custom cron

apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/socket-server/handlers/subblocks.ts, apps/sim/stores/operation-queue/store.ts
Remove all pending operations related to deleted block from queue so others can run without these retries blocking the queue and triggering connection warning.
Delete a block with and edge that goes into it and out of it. And do other stuff after like adding a new block. Connection warning will trigger until cascading failures are all out of the queue.
=> fix(sockets): delete block edge case 

apps/sim/app/api/workflows/[id]/duplicate/route.ts
Fixed the 404 error for duplicating a workflow where the user is not the owner. Now users with admin or write permissions can duplicate.
Test in staging.
=> fix: permissions check for duplicating workflow

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/document-selector/document-selector.tsx
add loading logic for document selector for kb block, all other dropdowns had the same loading logic except this one
=> improvement(kb): add loading logic for document selector for kb block

apps/sim/app/api/users/me/settings/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/hooks/use-sub-block-value.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/general/general.tsx, apps/sim/db/schema.ts, apps/sim/stores/index.ts, apps/sim/stores/settings/general/store.ts, apps/sim/stores/settings/general/types.ts, apps/sim/stores/workflows/registry/store.ts, apps/sim/stores/workflows/subblock/store.ts, apps/sim/stores/workflows/subblock/types.ts, apps/sim/stores/workflows/subblock/utils.ts
Simplify Autofill Env Var logic. 
- Previously: Had a store mapping that overrode API Key using a useEffect based on provider. Detected whether it was cleared by the user and marked clears. Didn't work because of race conditions between useEffects and mapping was unreliable. 
- Simplified behavior: Don't clear API Key on switching between same providers -- so convenience is still there to pick model within same provider after API key entered. But clear when switching to different provider. Requires no complex state management. 
https://github.com/user-attachments/assets/81c14475-6d52-4e8f-a382-afa6cb5caa40
=> fix(autofill-env-vars): simplify/remove logic to not cause useEffect overwrites

README.md, docker-compose.local.yml, docker-compose.prod.yml
Fixed docker container healthchecks, added instructions to README for pgvector
Fixes #720, #658 
Tested manually to ensure the realtime server works now with healthchecks in place.
=> fix(docker): fixed docker container healthchecks, added instructions to README for pgvector

apps/sim/next.config.ts
We had an issue where the NEXT_PUBLIC_SOCKET_URL was not being picked up properly and this is because t3-oss was not transpiled in the standalone build, and the runtime envvars were undefined and led to fallbacks. This worked if you didn't have a remote socket server url, but didn't used to work if you had the socket server running elsewhere with a standalone build.
Tested manually with a script to ensure that we were grabbing the correct socket url.
=> fix(config): add t3 to list of transpiled packages to ensure that envvars are picked up correctly

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/condition-input.tsx
Fixed condition block dropdown not showing in conditions. 
=> fix(condition): fixed condition block dropdown

apps/sim/app/api/webhooks/test/route.ts, apps/sim/app/api/webhooks/trigger/[path]/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/components/providers/microsoftteams.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/webhook.tsx, apps/sim/blocks/blocks/webhook.ts, apps/sim/lib/webhooks/utils.ts
MS Teams Webhook with secret configuration. 
https://github.com/user-attachments/assets/aa5803a2-09d7-47a3-8209-d1f73bfd03c7
=> feat(webhooks): ms teams webhook

apps/sim/lib/webhooks/utils.ts
Doesn't say error processing request even though it succeeds for MS teams Webhook.
=> fix(teams-webhook): response json needs type

apps/sim/lib/webhooks/utils.ts
Remove await before executing webhooks -- so acks are sent immediately back. 
https://github.com/user-attachments/assets/baf9bb65-d5cc-4730-95fb-51338361532e
=> fix(webhook): immediate acks from webhooks

apps/sim/lib/security/csp.ts, apps/sim/next.config.ts
- created csp util file that holds the csp for organization
- added google docs too prevent `docs.google.com refused to connect`
Tested manually to ensure we can still call all of these endpoints
=> fix(csp): created csp utils file that holds the csp for organization

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/chat/chat.tsx
Added the ability to reuse queries, focus cursor for continuous conversation
=> improvement(chat-panel): added the ability to reuse queries, focus cursor for continuous conversation

apps/sim/app/api/logs/enhanced/route.ts
Make logs scoped to workspace perms.
=> improvement(logs): make perms workspace scoped

apps/sim/lib/webhooks/utils.ts
Readding what was accidentally deleted in https://github.com/simstudioai/sim/pull/745
=> fix(webhooks): readd immediate acks

.github/workflows/ci.yml
- use migrate instead of push for ci
- marked 0-58 as applied in personal, staging, & prod so ci will just apply 59 and then when we use migrate moving forward, it will mark it as applied when the ci runs migrate
- This prevents us from the interactive terminal issue when running push
Tested manually in personal & dev.
=> fix(drizzle): use migrate instead of push for ci

apps/sim/app/api/logs/cleanup/route.ts, apps/sim/app/api/logs/enhanced/route.ts, apps/sim/db/migrations/0061_swift_doctor_spectrum.sql, apps/sim/db/migrations/meta/0061_snapshot.json, apps/sim/db/migrations/meta/_journal.json, apps/sim/db/schema.ts, apps/sim/lib/logs/enhanced-execution-logger.ts, apps/sim/lib/logs/types.ts
Remove unused workflow_execution_blocks table since block executions are part of trace spans.
Test regular execution and make sure logs show up.
=> improvement(cleanup): remove workflow_execution_blocks table

apps/sim/app/api/workflows/[id]/execute/route.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts
Pass child workflow variables in correctly for workflow in workflow block.
https://github.com/user-attachments/assets/8ba81164-f81a-4f90-9f92-091e1b458db3
=> fix(workflow-in-workflow): variables not accessible in child workflow 

.github/workflows/build.yml
Manifest not using right tags by arch -- fix by getting tags as variable.
=> fix(create-manifest): manifest not using right tags by arch

.github/workflows/build.yml
- fix(create-manifest): manifest not using right tags by arch (#793)
=> v0.3.13: fix create-manifest job

apps/sim/next.config.ts
- fix docs.google.com refused to connect issue by chaging COOP to same-origin-allow-popups, which allows popups you open to communicate and send back file selection
Tested manually in incognito browser to prevent browser caching.
=> fix(picker): fix docs.google.com refused to connect issue

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/control-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-workflow-execution.ts, apps/sim/executor/index.test.ts, apps/sim/executor/index.ts
Added the ability to cancel a run once its been launched. This prevents users with longer workflows from having to wait until the entire run is complete. Speeds up iteration.
https://github.com/user-attachments/assets/933771a6-1a7e-4cc7-9d0f-4c0bd8b79699
=> feat(worfklow): added cancellation after launching manual execution

apps/sim/lib/webhooks/utils.ts
No MS Teams immediate ack mechanism.
=> fix(teams): no immediate acks for ms teams webhook

README.md
=> fix(assets): update README.md

apps/sim/app/api/webhooks/[id]/route.ts, apps/sim/app/api/webhooks/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/components/webhook-modal.tsx
- On copying before saving -- a re-render caused webhook url to be regenerated. This PR fixes that bug. 
- Auth checks were just ownership -- didn't check permissions table. Also fixed in this PR. 
Open up webhook modal -- and click on copy url button - should not generate a new URL each time.
=> fix(webhook-modal): on copy do not change webhook url, fix auth to use regular perms system

.gitignore, apps/sim/components/emails/batch-invitation-email.tsx, helm/sim/.helmignore, helm/sim/Chart.yaml, helm/sim/README.md, helm/sim/examples/values-aws.yaml, helm/sim/examples/values-azure.yaml, helm/sim/examples/values-development.yaml, helm/sim/examples/values-external-db.yaml, helm/sim/examples/values-gcp.yaml, helm/sim/examples/values-production.yaml, helm/sim/templates/NOTES.txt, helm/sim/templates/_helpers.tpl, helm/sim/templates/deployment-app.yaml, helm/sim/templates/deployment-ollama.yaml, helm/sim/templates/deployment-realtime.yaml, helm/sim/templates/gpu-device-plugin.yaml, helm/sim/templates/hpa.yaml, helm/sim/templates/ingress.yaml, helm/sim/templates/networkpolicy.yaml, helm/sim/templates/serviceaccount.yaml, helm/sim/templates/servicemonitor.yaml, helm/sim/templates/services.yaml, helm/sim/templates/shared-storage.yaml, helm/sim/templates/statefulset-postgresql.yaml, helm/sim/templates/telemetry.yaml, helm/sim/values.schema.json, helm/sim/values.yaml, package.json
Added helm charts for self-hosting, with examples for GCP, Azure, and AWS
Fixes #391 
Tested manual deployment to ensure everything works as advertised.
=> feat(helm): added helm charts for self-hosting

apps/sim/app/layout.tsx
add rb2b only for our platform, not for self-hosted users. also modified the vercel analytics to run on our hosted app
N/A
=> feat(landing): add rb2b

apps/sim/app/layout.tsx, apps/sim/lib/env.ts, apps/sim/lib/security/csp.ts, apps/sim/next.config.ts
add redirects to maintain API routes with old host, allows users to still call old API endpoints but have the URL resolve to sim.ai
=> fix(domain): add redirects to maintain API routes with old host

apps/sim/app/api/telemetry/route.ts, apps/sim/instrumentation-node.ts, apps/sim/lib/telemetry.ts, apps/sim/next.config.ts, apps/sim/package.json, apps/sim/telemetry.config.ts
fix telemetry endpoint, only add redirects for hosted version
=> fix(domain): fix telemetry endpoint, only add redirects for hosted version

apps/sim/app/workspace/[workspaceId]/w/components/search-modal/hooks/use-search-navigation.ts, apps/sim/app/workspace/[workspaceId]/w/components/search-modal/search-modal.tsx
fixed search modal keyboard nav to include tools and blocks 
https://github.com/user-attachments/assets/3da75508-a2ea-4f24-aaa9-efb51acbcbef
=> fix(search-modal): fixed search modal keyboard nav

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/document-tag-entry/document-tag-entry.tsx
Existing UI for KB Block Create Document Tool to add tags not great + doesn't work with dark mode. 
New UI uses Table format as suggested
=> improvement(doc-tags-subblock): use table for doc tags subblock in create_document tool for KB

README.md, apps/sim/app/(landing)/components/sections/footer.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/document-tag-entry/document-tag-entry.tsx, apps/sim/components/emails/footer.tsx, apps/sim/lib/security/csp.ts, apps/sim/socket-server/database/operations.ts
- fixed rb2b csp
- fixed overly-verbose logs 
- fixed x URLs
N/A
=> fix(bugs): fixed rb2b csp, fixed overly-verbose logs, fixed x URLs

apps/sim/app/api/chat/utils.test.ts, apps/sim/app/api/chat/utils.ts, apps/sim/app/chat/[subdomain]/hooks/use-chat-streaming.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-workflow-execution.ts, apps/sim/contexts/socket-context.tsx, apps/sim/executor/index.test.ts, apps/sim/executor/index.ts, apps/sim/lib/security/csp.ts, apps/sim/middleware.ts, apps/sim/next.config.ts
- **fix(deployed-chat): allow non-streaming responses in deployed chat, allow partial failure responses in deployed chat**
- **fix(csp): runtime variable resolution for CSP**
- **cleanup**
Allow non-streaming responses in deployed chat, allow partial failure responses in deployed chat
Tested manually to ensure we can grab chat output for non-streaming blocks as well as streaming ones in the deployed chat and the chat panel. They behave the exact same. Also added tests for it.
=> fix(deployed-chat): allow non-streaming responses in deployed chat, allow partial failure responses in deployed chat

apps/sim/hooks/use-collaborative-workflow.ts
Fix duplicate block operation for sockets client side handler to use collaborativeSetSubblockValue instead of directly setting store values. This makes sure it enters and is processed by ops queue correctly. 
https://github.com/user-attachments/assets/05a8e6b1-70d5-4390-a2d9-14031f7b440a
=> fix(sockets): duplicate block op should go through debounced path

apps/sim/contexts/socket-context.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/socket-server/handlers/subblocks.ts, apps/sim/stores/operation-queue/store.ts
Batch subblock updates to clear client side queue faster for block duplications. 
Test duplicating 10 blocks in a row.
=> improvement(sockets): add batch subblock updates for duplicate to clear queue faster

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/chat-deploy.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/components/subdomain-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/components/success-view.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/hooks/index.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/hooks/use-chat-deployment.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/hooks/use-image-upload.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/chat-deploy/hooks/use-subdomain-validation.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/deploy-modal.tsx, apps/sim/components/ui/image-upload.tsx, apps/sim/components/ui/index.ts, apps/sim/next.config.ts, apps/sim/providers/utils.ts, apps/sim/stores/ollama/store.ts
added new image upload component, fixed some state issues with success view
=> fix(chat-deploy): added new image upload component, fixed some state issues with success view

apps/sim/app/api/logs/route.ts, apps/sim/app/workspace/[workspaceId]/logs/logs.tsx, apps/sim/db/migrations/0064_elite_hedge_knight.sql, apps/sim/db/migrations/meta/0064_snapshot.json, apps/sim/db/migrations/meta/_journal.json, apps/sim/db/schema.ts
- Permissions join was taking a while. Rearranged query to not have where class but filter as part of join to actually use index.
- Also removed two unused indices.
- Consolidated useEffects to make one less fetch logs call 
- Remove artificial minLoadingTime timeout
Tested loading logs
=> fix(logs-page): optimize logs retrieval queries, consolidate useEffects to prevent dup calls

apps/sim/app/api/knowledge/search/route.test.ts, apps/sim/app/api/knowledge/search/route.ts, apps/sim/app/api/knowledge/search/utils.test.ts, apps/sim/app/api/knowledge/search/utils.ts, apps/sim/blocks/blocks/knowledge.ts, apps/sim/tools/index.ts, apps/sim/tools/knowledge/search.ts
made query optional, so either query or tags or both can be provided. previously, the search query was required but now that we have tags, users should be able to filter with only tags
if the user provides tags + query, we use both. vector similarity and tag filtering happen together in a single query
if the user provides only tags, we don't do vector search
if the user provides only query, we don't include the tags in the query
if the user provides nothing, we throw a descriptive error that reads "Please provide either a search query or tag filters to search your knowledge base"
Added unit tests, also tested many times manually
https://github.com/user-attachments/assets/dc312dab-8a80-4476-b5ef-2cf63b39d14a
=> fix(kb-search): made query optional, so either query or tags or both can be provided

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/blocks/blocks/agent.ts
add shimmer to long-input while isStreaming, better prompt for system prompt generation
https://github.com/user-attachments/assets/aa10dec7-ecbb-4e91-b158-45a396323178
=> fix(wand): add shimmer to long-input while isStreaming, better prompt for system prompt generation

apps/sim/app/api/copilot/methods/route.ts, apps/sim/app/api/copilot/tools/other/online-search.ts, apps/sim/app/api/copilot/tools/user/set-environment-variables.ts, apps/sim/app/api/copilot/tools/workflow/build-workflow.ts, apps/sim/app/api/copilot/tools/workflow/edit-workflow.ts, apps/sim/app/api/copilot/tools/workflow/get-user-workflow.ts, apps/sim/lib/env.ts
Brief description of what this PR does and why.
Fixes #(issue)
How has this been tested? What should reviewers focus on?
=> fix(copilot): remove process.env

apps/sim/app/api/billing/update-cost/route.ts, apps/sim/lib/env.ts, apps/sim/providers/utils.ts
Adds update billing endpoint for agent
Manually
=> feat(copilot): add billing endpoint

apps/docs/content/docs/tools/hunter.mdx
=> fix(docs): docs update for hunter.io 

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/webhook/webhook.tsx, apps/sim/blocks/blocks/webhook.ts
Gmail credential should have been persisted + injected using subblock system -- not through webhook provider config. 
This previously affected the case where credentials already existed but were not actually connected via a webhook block itself. 
Tested by using ngrok + manually triggering gmail polling job.
=> fix(gmail-webhook): gmail credential injection issue with webhook block

apps/sim/app/api/copilot/chat/route.ts
Adds user name to prompt
Manual testing
=> improvement(copilot): adds user info

apps/sim/blocks/blocks/file.ts, apps/sim/blocks/blocks/mistral_parse.ts
Fixed file upload URL required
=> fix(file-upload): fixed file upload URL required

apps/sim/providers/models.ts
add openai oss models for groq
https://github.com/user-attachments/assets/879d45a3-7800-4a62-a21e-9e113c2bec05
=> feat(models): add openai oss models

apps/sim/app/workspace/[workspaceId]/w/components/search-modal/hooks/use-search-navigation.ts, apps/sim/app/workspace/[workspaceId]/w/components/search-modal/search-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-selector/components/invite-modal/invite-modal.tsx
- **fix(invite): fixed invite modal**
- **fix(search-modal): fix search modal keyboard nav**
fixed invite modal, fix search modal keyboard nav. invite modal functionality broke after ui updates, keyboard nav in search modal was unintuitive
=> fix(invite): fixed invite modal, fix search modal keyboard nav

apps/sim/app/workspace/[workspaceId]/w/components/search-modal/hooks/use-search-navigation.ts, apps/sim/app/workspace/[workspaceId]/w/components/search-modal/search-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-selector/components/invite-modal/invite-modal.tsx, apps/sim/providers/models.ts
- **feat(models): add openai oss models (#880)**
- **fix(invite): fixed invite modal, fix search modal keyboard nav (#879)**
=> v0.3.19: openai oss models, invite & search modal fixes

apps/sim/app/api/knowledge/[id]/documents/[documentId]/tag-definitions/route.ts, apps/sim/app/api/knowledge/[id]/documents/route.ts, apps/sim/app/api/knowledge/[id]/next-available-slot/route.ts, apps/sim/app/workspace/[workspaceId]/knowledge/components/document-tag-entry/document-tag-entry.tsx, apps/sim/db/migrations/0067_safe_bushwacker.sql, apps/sim/db/migrations/meta/0067_snapshot.json, apps/sim/db/migrations/meta/_journal.json, apps/sim/db/schema.ts, apps/sim/hooks/use-next-available-slot.ts, apps/sim/hooks/use-tag-definitions.ts, apps/sim/lib/constants/knowledge.ts
- fix(kb-tag-slots): finding next slot, create versus edit differentiation (#882)
=> v0.3.20: KB Tag fixes

apps/sim/app/api/workflows/[id]/execute/route.test.ts, apps/sim/app/api/workflows/[id]/execute/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/lib/workflows/db-helpers.ts, apps/sim/trigger/workflow-execution.ts
- Deployed API -- Async and Sync were not using Deployed State
- Enabled vs Disabled came from live block state rather than deployed state
Tested deploying as API and running queries and making sure it wasn't using live state.
=> fix(deployed-state): use deployed state for API sync and async execs, deployed state modal visual for enabled/disabled

apps/sim/app/api/auth/oauth/connections/route.ts, apps/sim/app/api/billing/route.ts, apps/sim/app/api/files/serve/[...path]/route.ts, apps/sim/app/api/folders/[id]/route.ts, apps/sim/app/api/folders/route.ts, apps/sim/app/api/logs/route.ts, apps/sim/app/api/organizations/[id]/route.ts, apps/sim/app/api/organizations/[id]/workspaces/route.ts, apps/sim/app/api/templates/[id]/route.ts, apps/sim/app/api/templates/route.ts, apps/sim/app/api/users/me/settings/route.ts, apps/sim/app/api/workspaces/route.ts, helm/sim/examples/values-production.yaml
Remove force-dynamic from nextjs routes that don't need it. This was causing detached state issues and infinite loop for `getSession()` calls
1. /api/workspaces/route.ts - User workspace lists don't change frequently, expensive DB queries benefit from caching.
2. /api/templates/route.ts - Shared templates are read-heavy, stable content that changes rarely.
3. /api/templates/[id]/route.ts - Individual templates are static content once created.
4. /api/users/me/settings/route.ts - User preferences change infrequently, perfect for caching.
5. /api/organizations/[id]/route.ts - Organization details are stable, expensive queries benefit from caching.
6. /api/organizations/[id]/workspaces/route.ts - Organization workspace lists are relatively stable with complex queries.
7. …
=> fix(dynamic): remove force-dynamic from routes that don't need it

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/export-controls/export-controls.tsx, apps/sim/lib/environment.ts, apps/sim/stores/workflows/yaml/store.ts
Export waits for complete workflow state (fixes premature/empty exports)
Manual testing
=> fix(agent): export waits for complete workflow state

apps/sim/app/api/copilot/methods/route.test.ts, apps/sim/app/api/copilot/methods/route.ts, apps/sim/app/api/yaml/diff/create/route.ts, apps/sim/app/api/yaml/diff/merge/route.ts, apps/sim/lib/copilot/tools/client-tools/get-user-workflow.ts, apps/sim/lib/copilot/tools/registry.ts, apps/sim/lib/copilot/tools/server-tools/workflow/edit-workflow.ts, apps/sim/lib/copilot/tools/server-tools/workflow/get-user-workflow.ts, apps/sim/lib/environment.ts, apps/sim/stores/copilot/store.ts, apps/sim/stores/workflow-diff/store.ts
Adds incremental edits to copilot functionality
Manual testing
=> improvement(copilot): incremental edits

apps/sim/lib/env.ts, apps/sim/services/queue/RateLimiter.test.ts, apps/sim/services/queue/RateLimiter.ts, apps/sim/services/queue/types.ts, helm/sim/values.yaml
Make rate limits configurable via environment variables, default values are what we had before as magic number so no need to set them anywhere
N/A
=> feat(rate-limits): make rate limits configurable via environment variables

apps/sim/lib/branding/metadata.ts
fixed build, previously assumed that it had access to NEXT_PUBLIC_APP_URL at runtime but it isn't set in CI
NA
=> fix(build): fixed build

apps/sim/app/api/schedules/[id]/route.ts, apps/sim/app/api/schedules/[id]/status/route.ts, apps/sim/app/api/schedules/execute/route.ts, apps/sim/app/api/schedules/route.test.ts, apps/sim/app/api/schedules/route.ts
Viewing schedule info was giving 403 since it was only checking ownership of workflow. Add logging for pre-execution failures. 
Tested manually by sharing workflow and viewing on User B.
=> fix(schedules-perms): use regular perm system to view/edit schedule info

apps/sim/app/api/help/route.ts, apps/sim/lib/auth.ts, apps/sim/lib/email/mailer.ts
update mailer to use the EMAIL_DOMAIN instead of deriving the email from the NEXT_PUBLIC_APP_URL
=> fix(mailer): update mailer to use the EMAIL_DOMAIN

apps/sim/app/(auth)/signup/signup-form.tsx, apps/sim/lib/auth.ts
manual OTP instead of better-auth
=> fix(email): manual OTP instead of better-auth

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/chat/components/chat-file-upload.tsx
fix chat attachments style in dark mode, previously the text was not readable
N/A
=> fix(chat): fix chat attachments style in dark mode

apps/sim/executor/handlers/workflow/workflow-handler.test.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts, apps/sim/executor/index.test.ts, apps/sim/executor/index.ts
- same child workflow executing in parallel with workflow block
- would previously cause cyclical dependency error
- fixed run button prematurely showing completion before child workflows completed
- would previously show the run was completed before all the child workflows had actually completed 
- prevent child worklfows from touching the activeBlocks & layer logic in the parent executor
- would not show pulsing since child workflows executor was touching the global activeBlocks set
- surface errors from child workflows
- child workflow errors do not get surfaced to the main workflow
https://github.com/user-attachments/assets/d8b70dd7-1bd9-4b3d-b8bb-b4e172a2d940
=> fix(workflow-block): improvements to pulsing effect, active execution state, and running workflow blocks in parallel

apps/sim/components/ui/tag-dropdown.tsx
fix values for parallel & loop blocks, was not showing index and currentItem
Before:
After:
=> fix(tag-dropdown): fix values for parallel & loop blocks

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/console/components/console-entry/console-entry.tsx, apps/sim/executor/index.ts, apps/sim/executor/resolver/resolver.ts, apps/sim/stores/panel/console/types.ts
Added iteration count to the parallell & loop console entries
=> improvement(console): added iteration info to console entry for parallel/loop

apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/knowledge-tags/knowledge-tags.tsx
fixed tags hover effect to match logs-filters
Manually
=> fix(kb-ui): fixed tags hover effect

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/subflows/components/iteration-badges/iteration-badges.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/code.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/combobox.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/short-input.tsx, apps/sim/components/ui/tag-dropdown.tsx
The closing bracket ('>') was triggering an effect to close the tag dropdown, that was racing with the entry of the last character. Could be the cause of the bug. Use live dom tracking in the tag dropdown to prevent this. Also move set cursor before store value setter for extra precaution.
Tested manually typing out variable values.
=> fix(tag-dropdown): last char dropped bug

apps/sim/lib/auth.ts, apps/sim/lib/env.ts
Reverting redis session management changes here #934  since Sockets auth is failing for unknown reason. 
Tested using ngrok + staging.
=> v0.3.24: revert redis session management change

apps/sim/tools/http/request.ts, apps/sim/tools/index.ts
=> Revert "fix(api): fix api block"

apps/sim/app/api/proxy/route.ts, apps/sim/tools/__test-utils__/test-tools.ts, apps/sim/tools/http/request.ts, apps/sim/tools/index.ts, apps/sim/tools/utils.ts
API Block Fixes
Manually with GET and POST
=> fix(double-read): API Block

apps/sim/app/api/files/multipart/route.ts, apps/sim/app/api/files/presigned/route.ts, apps/sim/app/api/files/upload/route.ts, apps/sim/app/workspace/[workspaceId]/knowledge/[id]/components/upload-modal/upload-modal.tsx, apps/sim/app/workspace/[workspaceId]/knowledge/hooks/use-knowledge-upload.ts
- Multipart file uploads
- File upload retries
- Batched file uploads
- Add auth to file upload routes
- Upload error logging
- Upload progress ui
Fixes #(issue)
Manual testing
=> improvement(uploads): add multipart upload + batching + retries

apps/sim/app/api/proxy/route.ts, apps/sim/tools/__test-utils__/test-tools.ts, apps/sim/tools/http/request.ts, apps/sim/tools/index.ts, apps/sim/tools/utils.ts
- reverted last commit with stringification, easier solution without response cloning or double reading or stringifying
- mock response is more efficient than response cloning 
=> fix(api): fix api post and get without stringifying

apps/sim/executor/handlers/workflow/workflow-handler.test.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts, apps/sim/executor/index.test.ts
=> Revert "fix(workflow-block): revert change bubbling up error for workflow block"

apps/sim/app/api/auth/oauth/token/route.test.ts, apps/sim/app/api/auth/oauth/token/route.ts, apps/sim/app/api/tools/drive/file/route.ts, apps/sim/app/api/tools/google_calendar/calendars/route.ts, apps/sim/app/api/tools/linear/projects/route.ts, apps/sim/app/api/tools/linear/teams/route.ts, apps/sim/app/api/tools/microsoft-teams/channels/route.ts, apps/sim/app/api/tools/microsoft-teams/chats/route.ts, apps/sim/app/api/tools/microsoft-teams/teams/route.ts, apps/sim/app/api/tools/slack/channels/route.ts, apps/sim/lib/auth/credential-access.ts, apps/sim/tools/google_sheets/append.ts, apps/sim/tools/google_sheets/read.ts, apps/sim/tools/google_sheets/update.ts, apps/sim/tools/google_sheets/write.ts, apps/sim/tools/index.ts
- Reuse authorizeCredentialUse helper everywhere to reduce code surface area 
- Fix google sheets url splitting bug
Manually
=> improvement(credentials-security): use clear credentials sharing helper, fix google sheets block url split bug

apps/sim/app/api/auth/oauth/token/route.test.ts, apps/sim/app/api/auth/oauth/token/route.ts, apps/sim/app/api/tools/drive/file/route.ts, apps/sim/app/api/tools/google_calendar/calendars/route.ts, apps/sim/app/api/tools/linear/projects/route.ts, apps/sim/app/api/tools/linear/teams/route.ts, apps/sim/app/api/tools/microsoft-teams/channels/route.ts, apps/sim/app/api/tools/microsoft-teams/chats/route.ts, apps/sim/app/api/tools/microsoft-teams/teams/route.ts, apps/sim/app/api/tools/slack/channels/route.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/settings-navigation/settings-navigation.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/settings-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx, apps/sim/executor/handlers/workflow/workflow-handler.test.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts, apps/sim/executor/index.test.ts, apps/sim/lib/auth/credential-access.ts, apps/sim/lib/env.ts, apps/sim/tools/google_sheets/append.ts, apps/sim/tools/google_sheets/read.ts, apps/sim/tools/google_sheets/update.ts, apps/sim/tools/google_sheets/write.ts, apps/sim/tools/index.ts
- **Revert "fix(workflow-block): revert change bubbling up error for workflow block" (#965)**
- **fix(billing): separate client side and server side envvars for billing (#966)**
- **improvement(credentials-sharing-security): cleanup and reuse helper to determine credential access (#968)**
=> v0.3.26: fix billing, bubble up workflow block errors, credentials security improvements

apps/sim/next.config.ts
Remove key field to make it valid route for redirect.
Must test by attempting deploy.
=> attempt to fix build issues

apps/sim/next.config.ts
attempt to fix build issues on vercel
=> attempt to fix build issues (#985)

apps/sim/stores/workflows/registry/store.ts
-  fix workflow detached on first load
- we set the activeWorkflowId immediately, and the check in the store checked only that and not if the workflow data was loaded in, now we modified it to check if the active workflow id matched the id provided, and that we have the workflow data then leave the loading state
https://github.com/user-attachments/assets/74222c1c-1f40-47fe-89d7-4ed484411d2c
=> fix(loading): fix workflow detached on first load

apps/sim/executor/handlers/agent/agent-handler.ts
stringify input into user prompt for agent, because the user input only takes a string which results in JSONs not being able to go in directly or numbers or anything besides strings
=> fix(agent): stringify input into user prompt for agent

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/channel-selector/channel-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/credential-selector/credential-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/confluence-file-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/google-drive-picker.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/jira-issue-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/microsoft-file-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/teams-message-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/file-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/folder-selector/components/folder-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/folder-selector/folder-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/project-selector/components/jira-project-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/project-selector/project-selector-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/hooks/use-foreign-credential.ts, apps/sim/tools/google_sheets/read.ts
Google blocks with folder / sheet pickers have confusing UI in the sense that you need to open this box which says Documents not available to open up the google driven picker. This PR changes that to directly open Google picker. 
Also greys out subblocks that are dependent on the credential until credential is selected.
Manually with Google Sheets and Drive Block.
https://github.com/user-attachments/assets/db05fc05-ebcd-40ee-b428-890576791563
=> fix(picker-ui): picker UI confusing when credential not set + Microsoft OAuth Fixes

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-workflow-execution.ts, apps/sim/executor/index.ts, apps/sim/stores/panel/console/store.ts, apps/sim/stores/workflows/workflow/store.test.ts
increase console max entries for larger workflows, this was causing a loop with 100 iterations to prematurely stop at 50 since that was the max entries for the console, bad UX
=> improvement(console): increase console max entries for larger workflows

apps/sim/tools/__test-utils__/test-tools.ts, apps/sim/tools/http/request.test.ts, apps/sim/tools/http/request.ts, apps/sim/tools/utils.test.ts, apps/sim/tools/utils.ts
add native support for form-urlencoded inputs into API block
Tested the same request here & in postman, ensured that the responses were identical
Before (even adding content-type to application/x-www-form-urlencoded it still used application/json):
After (respects the users content-type, converts json body into url encoded entry):
=> improvement(api): add native support for form-urlencoded inputs into API block

apps/docs/content/docs/tools/supabase.mdx, apps/sim/blocks/blocks/supabase.ts, apps/sim/tools/supabase/delete.ts, apps/sim/tools/supabase/get_row.ts, apps/sim/tools/supabase/insert.ts, apps/sim/tools/supabase/query.ts, apps/sim/tools/supabase/update.ts
added more verbose error logging for supabase operations
tested manually, screenshots below
=> improvement(supabase): added more verbose error logging for supabase operations

apps/sim/app/workspace/[workspaceId]/logs/components/trace-spans/trace-spans-display.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx, apps/sim/executor/handlers/workflow/workflow-handler.test.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts, apps/sim/executor/index.ts, apps/sim/lib/logs/execution/trace-spans/trace-spans.ts
added sub-workflow logs, updated trace spans UI, fix scroll behavior in workflow registry sidebar 
Workflow-in-workflow-in-workflow:
=> feat(logs): added sub-workflow logs, updated trace spans UI, fix scroll behavior in workflow registry sidebar 

apps/sim/app/api/auth/oauth/token/route.ts, apps/sim/app/api/auth/oauth/utils.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/google-drive-picker.tsx
Gdrive picker -- says cannot connect when it's opened and does a token refresh. It works after refresh. This PR fixes that condition. 
Airtable token checks cleanup since we're seeing refresh issues. 
=> fix(oauth): gdrive picker race condition, token route cleanup

apps/sim/app/api/auth/oauth/token/route.ts, apps/sim/app/api/auth/oauth/utils.ts, apps/sim/app/api/help/route.ts, apps/sim/app/api/knowledge/search/utils.test.ts, apps/sim/app/api/knowledge/search/utils.ts, apps/sim/app/api/knowledge/utils.test.ts, apps/sim/app/api/knowledge/utils.ts, apps/sim/app/api/wand-generate/route.ts, apps/sim/app/api/workspaces/invitations/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/google-drive-picker.tsx, apps/sim/components/emails/base-styles.ts, apps/sim/components/emails/batch-invitation-email.tsx, apps/sim/components/emails/help-confirmation-email.tsx, apps/sim/components/emails/index.ts, apps/sim/components/emails/render-email.ts, apps/sim/lib/auth.ts, apps/sim/lib/documents/document-processor.ts, apps/sim/lib/email/mailer.test.ts, apps/sim/lib/email/mailer.ts, apps/sim/lib/embeddings/utils.ts, apps/sim/lib/env.ts, apps/sim/package.json, bun.lock
allow usage of azure-openai for knowledgebase uploads and wand generation, also allow the user to select the model
Tested manually with an Azure deployment.
=> feat(azure-openai): allow usage of azure-openai for knowledgebase uploads and wand generation

apps/sim/next.config.ts, apps/sim/package.json, bun.lock
- Known bug: https://github.com/oven-sh/bun/issues/21137
- Solution: Revert NextJS upgrade until this is resolved
-  [x] Bug fix
created a new branch and tested the build action to ensure it deploys to docker
=> fix(nextjs): downgrade nextjs due to known issue with bun commonjs module bundling

apps/sim/app/api/help/route.ts, apps/sim/app/api/workspaces/invitations/route.test.ts, apps/sim/app/api/workspaces/invitations/route.ts, apps/sim/lib/auth.ts, apps/sim/lib/email/mailer.test.ts, apps/sim/lib/email/mailer.ts, apps/sim/lib/email/utils.test.ts, apps/sim/lib/email/utils.ts, apps/sim/lib/env.ts, bun.lock, helm/sim/values.schema.json, helm/sim/values.yaml
added FROM_EMAIL_ADDRESS envvar for ACS
Set FROM_EMAIL_ADDRESS and confirmed that I can send emails with that entire sender name with ACS, and tested our setup with resend as well.
=> fix(acs): added FROM_EMAIL_ADDRESS envvar for ACS

apps/sim/app/api/help/route.ts, apps/sim/app/api/workspaces/invitations/route.test.ts, apps/sim/app/api/workspaces/invitations/route.ts, apps/sim/db/migrations/0077_missing_doc_processing.sql, apps/sim/lib/auth.ts, apps/sim/lib/email/mailer.test.ts, apps/sim/lib/email/mailer.ts, apps/sim/lib/email/utils.test.ts, apps/sim/lib/email/utils.ts, apps/sim/lib/env.ts, helm/sim/values.schema.json, helm/sim/values.yaml
- **fix(migrations): add missing migration for document table (#1080)**
- **fix(acs): added FROM_EMAIL_ADDRESS envvar for ACS (#1081)**
- **fix(emails): remove unused useCustomFromFormat param (#1082)**
=> v0.3.35: migrations, custom email address support

apps/sim/app/api/auth/socket-token/route.ts, apps/sim/app/layout.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/file-selector/components/microsoft-file-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/hooks/use-sub-block-value.ts, apps/sim/app/workspace/layout.tsx, apps/sim/contexts/socket-context.tsx, apps/sim/hooks/use-user-permissions.ts, apps/sim/lib/auth-client.ts, apps/sim/lib/auth.ts, apps/sim/lib/session-context.tsx, apps/sim/serializer/index.ts, apps/sim/stores/subscription/store.ts
- Pass in session using session provider instead of using useSession everywhere. This is leading to issues when called repeatedly as part of useEffects or on remounts. 
- Fix hydration error cause by usage indicator
- Fix subblock race condition to make sure it waits for active workflow id
- Fix sockets token auth duplicate pings
- Fix microsoft oauth token fetch issue
- Fix "Starter Block required" error for webhook executions
Manually. Use platform for more than 10 minutes.
=> fix(infinite-get-session): pass session once per tree using session provider + multiple fixes

apps/sim/app/(auth)/components/social-login-buttons.tsx, apps/sim/app/(auth)/layout.tsx, apps/sim/app/(auth)/login/login-form.tsx, apps/sim/app/(auth)/signup/signup-form.tsx
modify signup and login pages to not show social sign in when not configured, increase logo size
Tested manually by commenting out github client id and google client id
=> improvement(signup): modify signup and login pages to not show social sign in when not configured, increase logo size

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/utils.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx
Cleaned up autoconnect edge cases
Manually
=> fix(autoconnect): cleaned up autoconnect

apps/sim/app/api/wand-generate/route.ts
remove unstable__noStore and remove, add additional logs for wand generation
=> fix(wand): remove unstable__noStore and remove, add additional logs for wand generation

apps/sim/app/llms.txt/route.ts, apps/sim/public/robots.txt
=> feat: added llms.txt and robots.txt

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/condition-input.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/stores/workflows/registry/store.ts
- Moving the subblocks around did not transfer edges along with it
- Duplication was not working with condition blocks. 
https://github.com/user-attachments/assets/ec3c70fa-d738-48c6-b60f-a224e74d41b1
=> fix(condition-block): edges not following blocks, duplicate issues

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/variables/variables.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/components/ui/tag-dropdown.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/stores/index.ts, apps/sim/stores/operation-queue/store.ts, apps/sim/stores/panel/variables/store.ts, apps/sim/stores/panel/variables/types.ts, apps/sim/stores/workflows/registry/store.ts
- Some minor cleanup for useCollaborativeWorkflow hook. 
- Fix variables persistence issues.
https://github.com/user-attachments/assets/b482856e-5df5-485f-ada6-bf5059871e71
=> fix(sockets): useCollabWorkflow cleanup, variables store logic simplification

apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/environment/environment.tsx
fix split for pasting envvars with query params
Fix splitting envvars with query params
=> fix(envvars): fix split for pasting envvars with query params

apps/sim/app/(auth)/signup/signup-form.test.tsx, apps/sim/app/(auth)/signup/signup-form.tsx, apps/sim/app/(auth)/verify/use-verification.ts
refetch session data on signup, since old session if just logged out of another acct was being used in the use-verify hook, and yielded invalid permissions. now, we refetch session data on signup to force grab the new user session instead.
=> fix(signup): refetch session data on signup

apps/sim/app/api/copilot/chat/route.ts, apps/sim/app/api/copilot/chats/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/copilot-message/copilot-message.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/user-input/user-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/welcome/welcome.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/copilot.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/credentials/credentials.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/settings-modal.tsx, apps/sim/components/ui/tool-call.tsx, apps/sim/lib/copilot/api.ts, apps/sim/lib/copilot/inline-tool-call.tsx, apps/sim/lib/copilot/process-contents.ts, apps/sim/lib/copilot/registry.ts, apps/sim/lib/copilot/tools/client/other/oauth-request-access.ts, apps/sim/lib/copilot/tools/client/user/set-environment-variables.ts, apps/sim/lib/copilot/tools/client/workflow/get-global-workflow-variables.ts, apps/sim/lib/copilot/tools/client/workflow/get-workflow-from-name.ts, apps/sim/lib/copilot/tools/client/workflow/list-user-workflows.ts, apps/sim/lib/copilot/tools/client/workflow/run-workflow.ts, apps/sim/lib/copilot/tools/client/workflow/set-global-workflow-variables.ts, apps/sim/lib/generate-chat-title.ts, apps/sim/stores/copilot/store.ts, apps/sim/stores/copilot/types.ts
Adds @ context to copilot
Also adds tools to view/set vars
Manual
=> feat(copilot):  context

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/user-input/user-input.tsx
Scope copilot context to workflows/kbs/chats from the workspace
Manual
=> fix(copilot): context filtering

apps/sim/app/api/organizations/[id]/members/[memberId]/route.ts, apps/sim/app/api/organizations/invitations/accept/route.ts, apps/sim/app/api/workspaces/invitations/accept/route.ts, apps/sim/app/globals.css, apps/sim/app/invite/[id]/invite.tsx, apps/sim/app/invite/invite-error/invite-error.tsx, apps/sim/lib/security/csp.ts
strengthen email invite validation logic, fix invite page UI
=> fix(security): strengthen email invite validation logic, fix invite page UI

apps/sim/app/api/knowledge/search/route.ts, apps/sim/app/api/knowledge/search/utils.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/create-menu/create-menu.tsx, apps/sim/tools/knowledge/search.ts, apps/sim/tools/knowledge/types.ts
Added document to return value of search. I also changed the create menu timeout delay to 300ms from 150ms. Slightly optimized speed of search route.
Run knowledge base search and confirm the document name is returned for each document.
=> improvement(knowledge): search returns document name

.github/workflows/trigger-deploy.yml
upgrade trigger.dev in gh action from 4.0.0 to 4.0.1 to match sdk version locally
NA
=> chore(deps): upgrade trigger.dev in gh action

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx
=> Revert "fix(cursor-and-input): fixes cursor and input canvas error"

apps/sim/app/api/wand-generate/route.ts
=> fix(wand): try switching runtime to nodejs

apps/sim/app/api/wand-generate/route.ts
Direct fetch on azure/openai endpoints
Manual
=> fix(wand): nodejs direct fetch

apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
- open settings when enterprise sub folks press usage indicator
-  previously, we open the settings indicator for users that are on the team plan and users that are blocked 
- now, we show the settings for enterprise users all around as well
=> fix(billing-ui): open settings when enterprise sub folks press usage indicator

apps/sim/background/knowledge-processing.ts, apps/sim/lib/env.ts, apps/sim/lib/knowledge/documents/service.ts
add adjustable concurrency and batching to uploads and embeddings
Defaults all remain standard config.
=> feat(kb): add adjustable concurrency and batching to uploads and embeddings

apps/sim/background/knowledge-processing.ts, apps/sim/lib/knowledge/documents/service.ts
=> improvement(kb): add fallbacks for kb configs

apps/sim/package.json, bun.lock, package.json
downgrade nextjs because bun bundling is incompatible with nextjs 15
downgrade nextjs
=> fix(deps): downgrade nextjs

apps/sim/background/knowledge-processing.ts, apps/sim/lib/knowledge/documents/service.ts, apps/sim/package.json, bun.lock, package.json
- **improvement(kb): add fallbacks for kb configs (#1199)**
- **fix(deps): downgrade nextjs (#1200)**
=> v0.3.42: kb config defaults, downgrade nextjs

apps/sim/db/migrations/0082_light_blockbuster.sql, apps/sim/db/migrations/meta/0082_snapshot.json, apps/sim/db/migrations/meta/_journal.json, apps/sim/db/schema.ts
added new indexes for improved session performance + other indexes that are recommended by better-auth to optimize for performance [ref](https://www.better-auth.com/docs/guides/optimizing-for-performance)
N/A
=> improvement(performance): added new indexes for improved session performance

apps/sim/app/(auth)/login/login-form.tsx, apps/sim/app/(auth)/signup/signup-form.test.tsx, apps/sim/app/(auth)/signup/signup-form.tsx, apps/sim/app/(auth)/verify/use-verification.ts, apps/sim/app/(auth)/verify/verify-content.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/credential-selector/credential-selector.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/trigger-config/components/trigger-config-section.tsx, apps/sim/components/ui/switch.tsx
Recently, we changed the way that we detect dark mode on our platform and we didn't have proper handling in certain areas to display the text correctly so it was unreadable. We've since changed this to have a specific dark mode style that will make it readable
Also, updated the login/signup
- Reset pass UI and error handling matches that of signup and login
- Auto-submit OTP when the digits are entered instead of making the user press enter
- Trim leading and trailing whitespace in name to avoid whitespace errors.
=> fix(ui): dark mode styling for switch, trigger modal UI, signup/login improvements with auto-submit for OTP

apps/sim/app/api/copilot/stats/route.ts, apps/sim/lib/copilot/tools/client/workflow/build-workflow.ts, apps/sim/lib/copilot/tools/client/workflow/edit-workflow.ts, apps/sim/stores/copilot/store.ts, apps/sim/stores/workflow-diff/store.ts
Fixes copilot stats
Fixes #(issue)
Manual
=> fix(copilot): fix copilot stats updates

apps/sim/app/api/copilot/stats/route.ts, apps/sim/lib/copilot/tools/client/workflow/build-workflow.ts, apps/sim/lib/copilot/tools/client/workflow/edit-workflow.ts, apps/sim/stores/copilot/store.ts, apps/sim/stores/workflow-diff/store.ts
=> v0.3.46: fix copilot stats updates

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/wand-prompt-bar/wand-prompt-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/code.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/short-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/components/code-editor/code-editor.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/components/custom-tool-modal/custom-tool-modal.tsx, apps/sim/executor/resolver/resolver.test.ts, apps/sim/executor/resolver/resolver.ts
added validation to not parse non-variables as variables in the code subblock, fixed styling of wand prompt bar and icons not visible in dark mode
Before:
After:
=> fix(code-subblock): added validation to not parse non-variables as variables in the code subblock

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/contexts/socket-context.tsx, apps/sim/stores/workflows/registry/store.ts, apps/sim/stores/workflows/subblock/store.ts
1. Duplicate overlay showing up after some idle time due to merge state logic. 
2. Subblock Loading race condition fix attempt. 
Manually
=> fix(hydration): duplicate overlay after idle + subblocks race condition

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/control-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/user-input/user-input.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx
Keeps reordering the sidebar. Keep it stable with alphabetical sort. 
Manually
=> fix(sidebar): re-ordering based on last edit is confusing

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/control-bar.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/copilot/components/user-input/user-input.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/sidebar.tsx, apps/sim/stores/workflows/registry/store.ts, apps/sim/stores/workflows/registry/types.ts
Order workflows by created at. 
Manually.
=> fix(sidebar): order by created at

apps/sim/providers/index.ts, apps/sim/providers/utils.ts
restored cost reporting for agent block in console entry, for hosted models we inject api key and in the check where we see if there is a `user-provided` api key, we incorrectly parsed our own keys as that
=> fix(cost): restored cost reporting for agent block in console entry

apps/sim/app/api/workspaces/invitations/[invitationId]/route.test.ts, apps/sim/app/api/workspaces/invitations/[invitationId]/route.ts, apps/sim/app/invite/[id]/utils.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/shared/usage-header.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/team-management/components/team-seats-overview/team-seats-overview.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/usage-indicator/usage-indicator.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/workspace-selector/components/invite-modal/invite-modal.tsx, apps/sim/components/ui/progress.tsx
add ability to resend invitations with cooldown, fixed UI in dark mode issues
=> feat(invitations): add ability to resend invitations with cooldown, fixed UI in dark mode issues

apps/docs/content/docs/blocks/router.mdx, apps/sim/blocks/blocks/router.ts, apps/sim/executor/handlers/router/router-handler.test.ts, apps/sim/executor/handlers/router/router-handler.ts
modify the content in the router response to be `prompt` instead, since it is not referenced in any workflows and did not accurately reflect what was in that field anyways
=> fix(router): change router block `content` to `prompt`

apps/sim/executor/resolver/resolver.test.ts, apps/sim/executor/resolver/resolver.ts
add back ability to reference root block like <start>, the stricter validation made it so that we could not reference things like `start`
=> fix(variables): add back ability to reference root block like <start>

README.md, apps/docs/content/docs/blocks/router.mdx, apps/sim/blocks/blocks/router.ts, apps/sim/db/migrations/0009_far_sharon_ventura.sql, apps/sim/executor/handlers/router/router-handler.test.ts, apps/sim/executor/handlers/router/router-handler.ts, apps/sim/executor/resolver/resolver.test.ts, apps/sim/executor/resolver/resolver.ts
- **improvement(docs): readme.md to mention .env setup for copilot setup**
- **fix(schedule-self-host): remove incorrect migration (#1260)**
- **fix(router): change router block `content` to `prompt` (#1261)**
- **fix(variables): add back ability to reference root block like <start> (#1262)**
=> 0.3.49: readme updates, router block and variables improvements

apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/folder-tree/components/workflow-item.tsx
Prevent missed clicks when rapidly switching workflows by gating navigation on active drag state rather than a transient drag-start flag. Keeps full-row drag-and-drop intact.
Fixes: N/A (surgical UX bugfix)
- Rapidly clicked multiple workflows (not intending to drag): each click navigates immediately.
- Intentionally dragged rows between folders and to root: DnD still works; payload (`workflow-ids`) unchanged.
- Shift+click multi-select, rename input, and hover edit button behaviors unchanged.
- Marketplace/editing states still disable drag as before.
N/A
=> fix(sidebar): prevent missed clicks during rapid workflow switching (keep row drag)

apps/sim/executor/handlers/workflow/workflow-handler.test.ts, apps/sim/executor/handlers/workflow/workflow-handler.ts
Process specific execution id stack doesn't make sense, and leads to arbitrary failures.
No functional change
=> fix(workflow-block): remove process specific circular dependency check

apps/sim/blocks/blocks/agent.ts, apps/sim/blocks/types.ts, apps/sim/hooks/use-collaborative-workflow.ts
Right now, we always set subblock values to null which isn't always appropriate. We need to be able to custom defaults for subblocks. Added this as a field into subblock configs. 
Manually. Used for temperature and tools in the Agent block right now.
=> improvement(subblock-defaults): custom defaults for subblocks if needed

apps/sim/app/api/workflows/[id]/yaml/route.ts
Follow other uses of SIM_AGENT_API_URL to allow easier local testing.
Manually
=> Fix(yaml env var): added env var fallback

apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/lib/naming.test.ts, apps/sim/lib/naming.ts, apps/sim/stores/workflows/workflow/store.ts
Implements client-side unique name generation for duplicated blocks, standardizing to "<Base> N" and preventing normalized collisions within a workflow. This keeps resolver/store normalization rules in sync and avoids server-side changes.
- Avoids confusing name collisions after duplicate, especially across variants that normalize equal (e.g., "My  Agent" vs "myagent").
- Ensures consistent UX across both duplicate entry points (collaborative and local store) with a single source of truth.
- Honors product decision to rely on client-side uniqueness only; server behavior unchanged.
- Added helper at `apps/sim/lib/naming.ts`:
- `normalizeBlockName(name)` – lowercase + strip spaces (parity with resolver/store).
- `generateUniqueBlockDuplicateName(existingNames, sourceName)` – produces "Base …
=> fix(naming): client-side unique duplicate names for blocks

apps/sim/executor/resolver/resolver.test.ts, apps/sim/executor/resolver/resolver.ts
Right now, we can only index into an 2d array with a function block. Variables for <array.values[0][0]> don't resolve in a non-function block—only <array.values[0]> does. This allows users to index into <array.values[0][0]>. Added strict regex to prevent "[" to be treated as index if <array.values[0][0]> would contain "[".
See video
https://github.com/user-attachments/assets/ef51a8f3-7917-4ac8-ab59-8940bfc6387e
=> improvement(array-index): resolved variables for 2d arrays

apps/sim/package.json, bun.lock
Plugin version back to stable version
Manually
=> fix(stripe): revert to stable versioning for better auth plugin

apps/sim/app/invite/components/index.ts, apps/sim/app/invite/components/layout.tsx
fix layout semantics on invite page
Build passes
=> fix(layout): fix layout semantics on invite page

apps/docs/package.json, apps/sim/package.json, bun.lock, package.json
=> fix(next-js): pin version

docker/app.Dockerfile
Dummy DB URL needed to build and push image.
=> fix(dockerfile): needs dummy db url

apps/docs/content/docs/en/tools/sharepoint.mdx, apps/sim/blocks/blocks/sharepoint.ts, apps/sim/lib/auth.ts, apps/sim/lib/oauth/oauth.ts, apps/sim/tools/registry.ts, apps/sim/tools/sharepoint/create_list.ts, apps/sim/tools/sharepoint/get_list.ts, apps/sim/tools/sharepoint/index.ts, apps/sim/tools/sharepoint/types.ts, apps/sim/tools/sharepoint/update_list.ts
Add list manipulation in sharepoint (get list, create list, update list)
Tested create list, read list, and update list
=> Improvement(sharepoint): added more operations in sharepoint

apps/sim/app/(auth)/verify/page.tsx, apps/sim/app/(auth)/verify/use-verification.ts, apps/sim/app/(auth)/verify/verify-content.tsx, apps/sim/lib/auth.ts, apps/sim/lib/email/mailer.ts, docker-compose.local.yml, docker-compose.prod.yml
verification skip for OTP in dev/docker was broken
1. Local development without email service = no verification
required
2. Any production deployment = verification always required
3. Any setup with email service = verification required (secure
default)
=> fix(verification): add OTP dev skip

apps/sim/components/emails/batch-invitation-email.tsx, apps/sim/components/emails/enterprise-subscription-email.tsx, apps/sim/components/emails/help-confirmation-email.tsx, apps/sim/components/emails/invitation-email.tsx, apps/sim/components/emails/otp-verification-email.tsx, apps/sim/components/emails/plan-welcome-email.tsx, apps/sim/components/emails/reset-password-email.tsx, apps/sim/components/emails/usage-threshold-email.tsx, apps/sim/components/emails/workspace-invitation.tsx
updated path for email assets to absolute rather than relative paths
=> fix(emails): updated path for email assets to absolute rather than relative paths

docker-compose.ollama.yml
fix ollama container for CPU vs GPU modem, there was a health check for `ollama`, which checked the GPU profile and therefore required that the user had a GPU
Fixes #1390 #1315 
Tested by running manually.
=> fix(ollama): fix ollama container for CPU vs GPU mode

apps/sim/tools/index.ts, apps/sim/tools/utils.test.ts
Fix tool execution JSON parsing error for non-JSON API responses.
Fixes issue where tools with transformResponse functions (like ArXiv tools) failed with JSON parsing errors when APIs return XML instead of JSON.
The root cause was the tool execution system was trying to parse ALL responses as JSON before calling transformResponse, causing failures for non-JSON APIs (ArXiv).
To fix it, I skipped automatic JSON parsing when transformResponse is present, allowing transformResponse to handle response parsing.
Added test case verifying transformResponse works with non-JSON responses. The test mocks a tool with transformResponse that uses response.text() to handle XML data, confirming the fix allows proper response handling while maintaining existing JSON API functionality (tested with basic …
=> fix(tools): allow transformResponse to handle non-JSON API responses

apps/sim/lib/auth.ts, apps/sim/lib/billing/calculations/usage-monitor.ts, apps/sim/lib/billing/core/usage.ts, apps/sim/lib/logs/execution/logger.ts
bar execution if limits cannot be determined, init user stats record on user creation instead of in stripe plugin. prev, we only init the user stats record in onCustomerCreate but now we can do it in a db hook outside of the stripe plugin so even self-hosted users with no stripe initialized can meter, even though it won't be enforced.
for users who are self-hosting & do not have corresponding user_stats records for their users, it will be created when persisting the execution logs, instead of doing an insert we do an upsert
Fixes #1393 
=> improvement(usage): bar execution if limits cannot be determined, init user stats record on user creation instead of in stripe plugin

apps/sim/tools/index.ts, apps/sim/tools/utils.test.ts
added transform response to handle non-json responses for internal tools
=> fix(tools): added transform response to handle non-json responses for internal tools

apps/sim/app/invite/components/status-card.tsx, apps/sim/app/not-found.tsx
=> feat(404): added 404 page

apps/sim/tools/arxiv/get_author_papers.ts, apps/sim/tools/arxiv/get_paper.ts, apps/sim/tools/arxiv/search.ts, apps/sim/tools/index.ts
fixed arxiv tools
Tested ArXiv and custom tools
=> fix(tools): fixed arxiv tools

apps/sim/lib/logs/execution/logger.ts, packages/db/migrations/0091_backfill_user_stats.sql
Just add missing user stats rows via migration
Manually by running migration
=> fix(missing-user-stats): missing user stats rows covered via migration

apps/sim/app/(auth)/verify/page.tsx, apps/sim/app/(auth)/verify/use-verification.ts, apps/sim/app/(auth)/verify/verify-content.tsx, apps/sim/lib/auth.ts, apps/sim/lib/env.ts, apps/sim/lib/environment.ts, helm/sim/examples/values-production.yaml, helm/sim/values.yaml
added environemnt variable to control enforcement of verified accounts, instead of using a complicated combination of hasEmailService & isProd. defaults to `FALSE` so maintains full backwards compatibility.
=> feat(otp): added environemnt variable to control enforcement of verified accounts

README.md, packages/db/.env.example
update readme.md to reflect new instructions for running locally
=> improvement(readme): update readme.md

apps/sim/lib/security/csp.ts
added terms, privacy, & logo URLs to CSP
=> fix(csp): added terms, privacy, & logo URLs to CSP

apps/sim/package.json, bun.lock
upgdate trigger.dev cli to latest version
=> chore(deps): upgdate trigger.dev cli

apps/sim/app/(landing)/privacy/page.tsx, apps/sim/app/(landing)/terms/page.tsx, apps/sim/lib/security/csp.ts, apps/sim/middleware.ts, apps/sim/next.config.ts
move redirects for terms/privacy to client-side redirects, because we were getting RSC CORS issues
=> fix(redirects): move redirects for terms/privacy to client-side redirects

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/floating-controls/floating-controls.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/general/general.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/hooks/use-undo-redo.ts, apps/sim/stores/settings/general/store.ts, apps/sim/stores/settings/general/types.ts, apps/sim/stores/undo-redo/index.ts, apps/sim/stores/undo-redo/store.ts, apps/sim/stores/undo-redo/types.ts, apps/sim/stores/undo-redo/utils.ts, apps/sim/stores/workflows/utils.ts, apps/sim/stores/workflows/workflow/store.ts, apps/sim/stores/workflows/workflow/types.ts
Undo/Redo for canvas editing.
https://github.com/user-attachments/assets/18ec1f23-df93-46d1-9ff6-902312b52e05
=> feat(undo-redo): undo/redo for canvas editing

apps/sim/app/api/copilot/training/route.ts, apps/sim/app/api/users/me/settings/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/training-controls/training-controls.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/training-controls/training-floating-button.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/training-controls/training-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/general/general.tsx, apps/sim/lib/copilot/tools/server/blocks/get-blocks-metadata-tool.ts, apps/sim/lib/copilot/tools/server/workflow/edit-workflow.ts, apps/sim/lib/env.ts, apps/sim/lib/workflows/training/compute-edit-sequence.ts, apps/sim/stores/copilot-training/store.ts, apps/sim/stores/settings/general/store.ts, apps/sim/stores/settings/general/types.ts, packages/db/migrations/0092_mighty_kinsey_walden.sql, packages/db/migrations/meta/0092_snapshot.json, packages/db/migrations/meta/_journal.json, packages/db/schema.ts
Training interface that will be enabled on Staging environment. 
Tested with indexer repo @Sg312
=> feat(copilot): add training interface 

apps/sim/app/api/chat/utils.ts, apps/sim/app/chat/[subdomain]/chat.tsx, apps/sim/app/chat/constants.ts, apps/sim/app/chat/hooks/use-chat-streaming.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-edge/workflow-edge.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-workflow-execution.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/blocks/blocks/input_trigger.ts, apps/sim/blocks/blocks/manual_trigger.ts, apps/sim/blocks/blocks/workflow_input.ts, apps/sim/blocks/registry.ts, apps/sim/executor/__test-utils__/executor-mocks.ts, apps/sim/executor/consts.ts, apps/sim/executor/handlers/condition/condition-handler.ts, apps/sim/executor/handlers/parallel/parallel-handler.ts, apps/sim/executor/index.ts, apps/sim/executor/loops/loops.test.ts, apps/sim/executor/loops/loops.ts, apps/sim/executor/parallels/parallels.test.ts, apps/sim/executor/parallels/parallels.ts, apps/sim/executor/parallels/utils.ts, apps/sim/executor/path/path.ts, apps/sim/executor/utils/connections.ts, apps/sim/executor/utils/virtual-blocks.ts, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/lib/workflows/triggers.ts, apps/sim/package.json, apps/sim/postcss.config.mjs, bun.lock
update parallel subflow to support conditional routing by the condition block & router
=> improvement(parallel): update parallel subflow to support conditional routing

apps/sim/next.config.ts, apps/sim/package.json, bun.lock
added turborepo, tailwind v3
N/A
=> feat(turbo): added turborepo, tailwind v3

apps/sim/app/api/copilot/api-keys/generate/route.ts, apps/sim/app/api/copilot/api-keys/route.ts, apps/sim/app/api/copilot/execute-copilot-server-tool/route.ts, apps/sim/app/api/copilot/tools/mark-complete/route.ts, apps/sim/app/api/yaml/autolayout/route.ts, apps/sim/app/api/yaml/diff/create/route.ts, apps/sim/app/api/yaml/diff/merge/route.ts, apps/sim/app/api/yaml/generate/route.ts, apps/sim/app/api/yaml/health/route.ts, apps/sim/app/api/yaml/parse/route.ts, apps/sim/app/api/yaml/to-workflow/route.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/copilot/copilot.tsx, apps/sim/lib/copilot/auth/permissions.ts, apps/sim/lib/copilot/tools/server/base-tool.ts, apps/sim/lib/copilot/tools/server/router.ts, apps/sim/lib/copilot/tools/server/user/get-environment-variables.ts, apps/sim/lib/copilot/tools/server/user/get-oauth-credentials.ts, apps/sim/lib/copilot/tools/server/user/set-environment-variables.ts
added session context checks in copilot tool calls for added security, to ensure user's have an authenticated context before the copilot executes tools on their behalf
Manually.
=> improvement(copilot): added session context checks in copilot tool calls

apps/sim/tools/google_drive/upload.ts, apps/sim/tools/google_drive/utils.ts
Creating a sheet in google drive didn't follow the proper syntax as it did for google sheets.
Tested with hummus
=> Fix(google drive): google sheets creating a file

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/lib/copilot/tools/server/workflow/build-workflow.ts
Fixes copilot diff store not loading diff
Manual
=> fix(copilot): fix diff store

.github/workflows/images.yml
- fix(ci): fix docker manifest build (#1494 )
=> fix(ci): fix docker manifest build

.github/workflows/ci.yml
Removes migrations ci to solve duplicate migrations problem with new infra
n/a
=> fix(ci): remove duplicate migration run

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/workflow.tsx, apps/sim/blocks/blocks/api_trigger.ts, apps/sim/blocks/blocks/chat_trigger.ts, apps/sim/blocks/blocks/input_trigger.ts, apps/sim/blocks/blocks/manual_trigger.ts, apps/sim/blocks/blocks/schedule.ts, apps/sim/lib/workflows/autolayout/utils.ts
- Generate trigger block with random uuid -- consistent with sidebar selection
- Add triggerAllowed flag to core triggers for copilot context 
- Fix isStarterBlock function to recognize new triggers in autolayout
- Other: General Improvement
Manually
=> improvement(triggers): uuid, autolayout, copilot context

apps/sim/app/api/workflows/[id]/autolayout/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/workflow-block.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/utils.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/utils/auto-layout.ts, apps/sim/lib/workflows/autolayout/containers.ts, apps/sim/lib/workflows/autolayout/incremental.ts, apps/sim/lib/workflows/autolayout/index.ts, apps/sim/lib/workflows/autolayout/layering.ts, apps/sim/lib/workflows/autolayout/positioning.ts, apps/sim/lib/workflows/autolayout/types.ts, apps/sim/lib/workflows/autolayout/utils.ts, apps/sim/stores/workflows/workflow/store.ts, apps/sim/stores/workflows/workflow/types.ts
- Don't align start triggers 
- Use live block heights / widths in autolayout algo
=> improvement(autolayout): use live block heights / widths for autolayout to prevent overlaps

.github/workflows/trigger-deploy.yml
Modifies trigger ci to capture correct version for upsert to ssm
Fixes #(issue)
n/a
=> fix(ci): capture correct deployment version output

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/combobox.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/input-mapping/input-mapping.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/knowledge-tag-filters/knowledge-tag-filters.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/long-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/short-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/starter/input-format.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/components/mcp-server-modal/mcp-server-modal.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/workflow-block/components/sub-block/components/tool-input/tool-input.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-accessible-reference-prefixes.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/knowledge-tags/knowledge-tags.tsx, apps/sim/components/ui/formatted-text.tsx, apps/sim/components/ui/tag-dropdown.tsx, apps/sim/executor/resolver/resolver.test.ts, apps/sim/executor/resolver/resolver.ts, apps/sim/lib/workflows/references.ts, apps/sim/serializer/index.ts
- Block references (e.g., <function1.result>) are now validated against accessible blocks before resolution - only references to connected/accessible blocks are highlighted in blue and resolved
- Inaccessible references remain as literal strings instead of throwing validation errors, following the principle that only highlighted references get resolved
- Removed validation errors from serializer and updated tests to match the new behavior where unconnected block references are left as-is rather than causing failures
Manually + Test suite
=> improvement(var-resolution): resolve variables with block name check and consolidate code

apps/sim/lib/env.ts, apps/sim/trigger.config.ts
increase maxDuration for background tasks to 10 min to match sync API executions. previously, the async executions had a timeout of 180s but we increase that to 10m to match the synchronous executions timeout
=> improvement(trigger): increase maxDuration for background tasks to 10 min to match sync API executions

apps/sim/middleware.ts
- update middleware to allow access to /chat regardless of auth status
- previously, authorized users were auto-redirected to the workspace & unauthorized users were redirected to the homepage
=> fix(redirects): update middleware to allow access to /chat regardless of auth status

.github/workflows/trigger-deploy.yml
update trigger.dev ci to only push to staging on merge to staging & for prod as well
Added provision to make deployment to trigger only happen on merges to the branches, not when PRs were made against branches
=> fix(ci): update trigger.dev ci to only push to staging on merge to staging & for prod as well

.github/workflows/trigger-deploy.yml, apps/sim/trigger.config.ts
Injects trigger project id var in correctly. Check for push done earlier so just removing it here.
Directly deploying locally
=> fix(trigger): inject project id env var in correctly

apps/sim/lib/workflows/db-helpers.ts, apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/rooms/manager.ts, packages/db/index.ts, packages/db/scripts/migrate-deployment-versions.ts, packages/db/scripts/register-sso-provider.ts
-  enforce SSL everywhere where a DB connection is established
- remove extraneous log that was flooding logs
=> improvement(db): enforce SSL everywhere where a DB connection is established

apps/sim/app/api/copilot/checkpoints/revert/route.test.ts, apps/sim/app/api/copilot/checkpoints/revert/route.ts, apps/sim/app/api/workflows/[id]/deployments/[version]/revert/route.ts, apps/sim/app/api/workflows/[id]/route.ts, apps/sim/app/api/workflows/[id]/state/route.ts, apps/sim/app/api/workflows/yaml/export/route.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/diff-controls.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/hooks/use-current-workflow.ts, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/utils/auto-layout.ts, apps/sim/contexts/socket-context.tsx, apps/sim/hooks/use-collaborative-workflow.ts, apps/sim/lib/workflows/db-helpers.test.ts, apps/sim/lib/workflows/db-helpers.ts, apps/sim/lib/workflows/diff/use-workflow-diff.ts, apps/sim/lib/workflows/json-sanitizer.ts, apps/sim/socket-server/database/operations.ts, apps/sim/stores/copilot/store.ts, apps/sim/stores/workflows/workflow/store.ts, apps/sim/stores/workflows/workflow/types.ts
Type issue with deployedStatus and deployedAt fields -- if workflow was deployed. This fixes that. 
Removed dead workflow state fields
=> fix(autolayout): type issue if workflow deployed + remove dead state code

apps/sim/tools/knowledge/create_document.ts
removed filename constraint from knowledgebase doc names, previously we had some constraints to the filename that are not hard restraints, since we store the file name as-is in the db
Manually.
=> fix(kb): removed filename constraint from knowledgebase doc names

apps/docs/app/[lang]/layout.tsx
fixed client-side export on fumadocs that was causing docs build to fail
Tested build manually.
=> fix(fumadocs): fixed client-side export on fumadocs

apps/sim/app/api/logs/route.ts, apps/sim/app/api/v1/logs/route.ts, apps/sim/socket-server/database/operations.ts
- remove writes to workflow updated_at on position updates for blocks, edges, & subflows 
- previosuly, every position update or any operation for that matter updated the workflow record int he wrofklow table
- this caused many different operations to contend for the same lock since they were all trying to update the updated_at timestamp of the same record. to resolve this, we removed the writes to updated_at on position changes and made it only for non position-update ops. this will significantly reduce the 200ms avg update time 
- for the logs, this was the pattern before
```
1. Scan ALL workflow_execution_logs (millions of rows)
2. Join to workflow table
3. Join to permissions WHERE user_id = X
4. Filter WHERE workspace_id = Y
5. Return 100 rows
```
- pattern now
```
1. Start with …
```
=> improvement(performance): remove writes to workflow updated_at on position updates for blocks, edges, & subflows

apps/sim/.env.example, apps/sim/app/api/logs/route.ts, apps/sim/app/api/v1/logs/route.ts, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/settings-navigation/settings-navigation.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/subscription/subscription.tsx, apps/sim/lib/env.ts, apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/rooms/manager.ts, packages/db/index.ts, packages/db/scripts/deregister-sso-provider.ts, packages/db/scripts/migrate-deployment-versions.ts, packages/db/scripts/register-sso-provider.ts
add more options for SSL connection, add envvar for base64 db cert. for users who don't set anything, nothing changes but for those who set DATABASE_SSL to non-nil value, we respect their option
Manually.
=> fix(db): add more options for SSL connection, add envvar for base64 db cert

packages/db/drizzle.config.ts
added SSL config to migrations container, to have parity with the primary app
Manually.
=> fix(db): added SSL config to migrations container

apps/sim/.env.example, apps/sim/drizzle.config.ts, apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/rooms/manager.ts, packages/db/drizzle.config.ts, packages/db/index.ts, packages/db/scripts/deregister-sso-provider.ts, packages/db/scripts/migrate-deployment-versions.ts, packages/db/scripts/register-sso-provider.ts
remove overly complex db connection logic
Manually
=> fix(db): remove overly complex db connection logic

apps/sim/app/api/files/presigned/route.ts
force kb uploads to use serve route instead of direct uploads/GETs since those caused sporadic failures with forbidden errors
=> fix(kb): force kb uploads to use serve route

apps/sim/lib/env.ts, apps/sim/next.config.ts
add rewrites for posthog reverse proxy routes unconditionally, remove unused POSTHOG_ENABLED envvar
=> fix(posthog): add rewrites for posthog reverse proxy routes unconditionally, remove unused POSTHOG_ENABLED envvar

apps/sim/app/layout.tsx, apps/sim/instrumentation-client.ts, apps/sim/lib/posthog/provider.tsx
added posthog provider instead of using nextjs instrumentation which was finnicky because of build-time environment variables
=> feat(posthog): added posthog provider instead of using nextjs instrumentation

apps/sim/app/(landing)/building/layout.tsx, apps/sim/app/(landing)/building/openai-vs-n8n-vs-sim/openai-n8n-sim.tsx, apps/sim/app/(landing)/components/footer/footer.tsx, apps/sim/app/theme-provider.tsx
- fix(blog): center footer, fix dark mode, fix avatar (https://github.com/simstudioai/sim/pull/1559)
=> v0.4.8: more blog

apps/sim/app/api/knowledge/[id]/route.test.ts, apps/sim/app/api/knowledge/[id]/route.ts, apps/sim/app/workspace/[workspaceId]/knowledge/[id]/base.tsx, apps/sim/app/workspace/[workspaceId]/knowledge/components/workspace-selector/workspace-selector.tsx, apps/sim/lib/knowledge/service.ts, apps/sim/stores/knowledge/store.ts
Fix switching workspaces for KB.
=> fix(kb-workspace-selector): allow switching assigned workspace for KB

apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/deploy-form/deploy-form.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/control-bar/components/deploy-modal/components/deployment-info/components/example-command/example-command.tsx, apps/sim/app/workspace/[workspaceId]/w/[workflowId]/components/panel/components/chat/components/output-select/output-select.tsx, apps/sim/app/workspace/[workspaceId]/w/components/sidebar/components/settings-modal/components/api-keys/api-keys.tsx
fixed curl example in deploy modal to reflect selected option
=> fix(curl-example): fixed curl example in deploy modal to reflect selected option

apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/rooms/manager.ts, packages/db/index.ts
reduce overall number of db max conncetions to incr performance
=> fix(db): reduce overall number of db max conncetions to incr performance

.github/workflows/publish-ts-sdk.yml, packages/ts-sdk/package.json, packages/ts-sdk/tsconfig.json, packages/ts-sdk/vitest.config.ts
=> fix(ts-sdk): fix job to publish ts sdk

.github/workflows/publish-python-sdk.yml, .github/workflows/publish-ts-sdk.yml, packages/ts-sdk/package.json
updated docs to reflect repo name
N/A
=> chore(docs): update docs

apps/sim/socket-server/database/operations.ts, apps/sim/socket-server/rooms/manager.ts, packages/db/index.ts
This reverts commit ae3a7f08653cd8d274157c51a6d307183e8f2efe.
=> fix(db): revert to dedicated sockets db connection establishment
